-- =====================================================================
-- BolãoEEL — Tabela de jogadores convocados para a Copa 2026
-- Seed com elencos oficiais das 48 seleções.
-- Idempotente: pode rodar mais de uma vez.
-- Execute DEPOIS de migration_copa2026.sql.
-- =====================================================================

begin;

-- Tabela
create table if not exists public.jogadores (
  id         uuid primary key default gen_random_uuid(),
  nome       text not null,
  selecao_id uuid not null references public.selecoes(id) on delete cascade
);
create index if not exists jogadores_selecao_id_idx on public.jogadores(selecao_id);

-- RLS
alter table public.jogadores enable row level security;
drop policy if exists "leitura publica" on public.jogadores;
create policy "leitura publica" on public.jogadores
  for select using (true);

-- Limpa seed anterior para ser idempotente
delete from public.jogadores;

-- =====================================================================
-- SEED: jogadores por seleção (nome, código FIFA)
-- =====================================================================

insert into public.jogadores (nome, selecao_id) values

-- Grupo A: MEX
('Guillermo Ochoa',    (select id from public.selecoes where codigo='MEX')),
('Carlos Acevedo',     (select id from public.selecoes where codigo='MEX')),
('Alejandro Rangel',   (select id from public.selecoes where codigo='MEX')),
('Jorge Sanchez',      (select id from public.selecoes where codigo='MEX')),
('Kevin Alvarez',      (select id from public.selecoes where codigo='MEX')),
('Jesus Gallardo',     (select id from public.selecoes where codigo='MEX')),
('Cesar Montes',       (select id from public.selecoes where codigo='MEX')),
('Johan Vasquez',      (select id from public.selecoes where codigo='MEX')),
('Edson Alvarez',      (select id from public.selecoes where codigo='MEX')),
('Carlos Rodriguez',   (select id from public.selecoes where codigo='MEX')),
('Hector Herrera',     (select id from public.selecoes where codigo='MEX')),
('Andres Guardado',    (select id from public.selecoes where codigo='MEX')),
('Hirving Lozano',     (select id from public.selecoes where codigo='MEX')),
('Alexis Vega',        (select id from public.selecoes where codigo='MEX')),
('Raul Jimenez',       (select id from public.selecoes where codigo='MEX')),
('Henry Martin',       (select id from public.selecoes where codigo='MEX')),
('Uriel Antuna',       (select id from public.selecoes where codigo='MEX')),
('Roberto Alvarado',   (select id from public.selecoes where codigo='MEX')),
('Orbelin Pineda',     (select id from public.selecoes where codigo='MEX')),
('Santiago Gimenez',   (select id from public.selecoes where codigo='MEX')),
('Alexis Fidalgo',     (select id from public.selecoes where codigo='MEX')),
('Charly Rodriguez',   (select id from public.selecoes where codigo='MEX')),
('Julian Quinones',    (select id from public.selecoes where codigo='MEX')),

-- Grupo A: RSA
('Ronwen Williams',    (select id from public.selecoes where codigo='RSA')),
('Veli Mothwa',        (select id from public.selecoes where codigo='RSA')),
('Grant Kekana',       (select id from public.selecoes where codigo='RSA')),
('Siyanda Xulu',       (select id from public.selecoes where codigo='RSA')),
('Nkosinathi Sibisi',  (select id from public.selecoes where codigo='RSA')),
('Nyiko Mobbie',       (select id from public.selecoes where codigo='RSA')),
('Terrence Mashego',   (select id from public.selecoes where codigo='RSA')),
('Thabiso Monyane',    (select id from public.selecoes where codigo='RSA')),
('Mothobi Mvala',      (select id from public.selecoes where codigo='RSA')),
('Teboho Mokoena',     (select id from public.selecoes where codigo='RSA')),
('Ethan Chislett',     (select id from public.selecoes where codigo='RSA')),
('Yusuf Maart',        (select id from public.selecoes where codigo='RSA')),
('Themba Zwane',       (select id from public.selecoes where codigo='RSA')),
('Lyle Foster',        (select id from public.selecoes where codigo='RSA')),
('Percy Tau',          (select id from public.selecoes where codigo='RSA')),
('Bongani Zungu',      (select id from public.selecoes where codigo='RSA')),
('Sphephelo Sithole',  (select id from public.selecoes where codigo='RSA')),
('Lebo Mothiba',       (select id from public.selecoes where codigo='RSA')),
('Sibusiso Vilakazi',  (select id from public.selecoes where codigo='RSA')),
('Evidence Makgopa',   (select id from public.selecoes where codigo='RSA')),
('Khuliso Mudau',      (select id from public.selecoes where codigo='RSA')),
('Elias Mokwana',      (select id from public.selecoes where codigo='RSA')),
('Fagrie Lakay',       (select id from public.selecoes where codigo='RSA')),

-- Grupo A: KOR
('Son Heung-min',      (select id from public.selecoes where codigo='KOR')),
('Kim Min-jae',        (select id from public.selecoes where codigo='KOR')),
('Hwang Hee-chan',     (select id from public.selecoes where codigo='KOR')),
('Hwang In-beom',      (select id from public.selecoes where codigo='KOR')),
('Lee Kang-in',        (select id from public.selecoes where codigo='KOR')),
('Jo Hyeon-woo',       (select id from public.selecoes where codigo='KOR')),
('Kim Seung-gyu',      (select id from public.selecoes where codigo='KOR')),
('Song Bum-keun',      (select id from public.selecoes where codigo='KOR')),
('Kim Moon-hwan',      (select id from public.selecoes where codigo='KOR')),
('Kim Tae-hwan',       (select id from public.selecoes where codigo='KOR')),
('Park Joo-ho',        (select id from public.selecoes where codigo='KOR')),
('Lee Tae-seok',       (select id from public.selecoes where codigo='KOR')),
('Lee Han-beom',       (select id from public.selecoes where codigo='KOR')),
('Cho Gue-sung',       (select id from public.selecoes where codigo='KOR')),
('Kim Ji-soo',         (select id from public.selecoes where codigo='KOR')),
('Bae Jun-ho',         (select id from public.selecoes where codigo='KOR')),
('Paik Seung-ho',      (select id from public.selecoes where codigo='KOR')),
('Yang Hyun-jun',      (select id from public.selecoes where codigo='KOR')),
('Eom Ji-sung',        (select id from public.selecoes where codigo='KOR')),
('Lee Dong-gyeong',    (select id from public.selecoes where codigo='KOR')),
('Oh Hyeon-gyu',       (select id from public.selecoes where codigo='KOR')),
('Lee Jun-seok',       (select id from public.selecoes where codigo='KOR')),
('Cho Gue-sung',       (select id from public.selecoes where codigo='KOR')),

-- Grupo A: CZE
('Tomas Vaclik',       (select id from public.selecoes where codigo='CZE')),
('Jiri Stanek',        (select id from public.selecoes where codigo='CZE')),
('Martin Jedlicka',    (select id from public.selecoes where codigo='CZE')),
('Vladimir Coufal',    (select id from public.selecoes where codigo='CZE')),
('Ladislav Krejci',    (select id from public.selecoes where codigo='CZE')),
('Jakub Brabec',       (select id from public.selecoes where codigo='CZE')),
('David Zima',         (select id from public.selecoes where codigo='CZE')),
('Jan Boril',          (select id from public.selecoes where codigo='CZE')),
('Tomas Holes',        (select id from public.selecoes where codigo='CZE')),
('Tomas Soucek',       (select id from public.selecoes where codigo='CZE')),
('Alex Kral',          (select id from public.selecoes where codigo='CZE')),
('Lukas Provod',       (select id from public.selecoes where codigo='CZE')),
('Jan Kuchta',         (select id from public.selecoes where codigo='CZE')),
('Patrik Schick',      (select id from public.selecoes where codigo='CZE')),
('Adam Hlozek',        (select id from public.selecoes where codigo='CZE')),
('Ondrej Lingr',       (select id from public.selecoes where codigo='CZE')),
('Mojmir Chytil',      (select id from public.selecoes where codigo='CZE')),
('Vaclav Cerny',       (select id from public.selecoes where codigo='CZE')),
('Petr Sevcik',        (select id from public.selecoes where codigo='CZE')),
('Filip Novak',        (select id from public.selecoes where codigo='CZE')),
('Martin Vitik',       (select id from public.selecoes where codigo='CZE')),
('Lukas Cerv',         (select id from public.selecoes where codigo='CZE')),
('Tomas Chory',        (select id from public.selecoes where codigo='CZE')),

-- Grupo B: CAN
('Milan Borjan',       (select id from public.selecoes where codigo='CAN')),
('Dayne St. Clair',    (select id from public.selecoes where codigo='CAN')),
('Maxime Crepeau',     (select id from public.selecoes where codigo='CAN')),
('Alphonso Davies',    (select id from public.selecoes where codigo='CAN')),
('Richie Laryea',      (select id from public.selecoes where codigo='CAN')),
('Kamal Miller',       (select id from public.selecoes where codigo='CAN')),
('Steven Vitoria',     (select id from public.selecoes where codigo='CAN')),
('Derek Cornelius',    (select id from public.selecoes where codigo='CAN')),
('Alistair Johnston',  (select id from public.selecoes where codigo='CAN')),
('Sam Adekugbe',       (select id from public.selecoes where codigo='CAN')),
('Atiba Hutchinson',   (select id from public.selecoes where codigo='CAN')),
('Stephen Eustaquio',  (select id from public.selecoes where codigo='CAN')),
('Jonathan Osorio',    (select id from public.selecoes where codigo='CAN')),
('Mark-Anthony Kaye',  (select id from public.selecoes where codigo='CAN')),
('Tajon Buchanan',     (select id from public.selecoes where codigo='CAN')),
('Junior Hoilett',     (select id from public.selecoes where codigo='CAN')),
('Jonathan David',     (select id from public.selecoes where codigo='CAN')),
('Cyle Larin',         (select id from public.selecoes where codigo='CAN')),
('Lucas Cavallini',    (select id from public.selecoes where codigo='CAN')),
('Liam Millar',        (select id from public.selecoes where codigo='CAN')),
('Jacob Shaffelburg',  (select id from public.selecoes where codigo='CAN')),
('Ismael Kone',        (select id from public.selecoes where codigo='CAN')),
('Theo Corbeanu',      (select id from public.selecoes where codigo='CAN')),

-- Grupo B: SUI
('Yann Sommer',        (select id from public.selecoes where codigo='SUI')),
('Gregor Kobel',       (select id from public.selecoes where codigo='SUI')),
('Jonas Omlin',        (select id from public.selecoes where codigo='SUI')),
('Manuel Akanji',      (select id from public.selecoes where codigo='SUI')),
('Nico Elvedi',        (select id from public.selecoes where codigo='SUI')),
('Fabian Schar',       (select id from public.selecoes where codigo='SUI')),
('Ricardo Rodriguez',  (select id from public.selecoes where codigo='SUI')),
('Silvan Widmer',      (select id from public.selecoes where codigo='SUI')),
('Kevin Mbabu',        (select id from public.selecoes where codigo='SUI')),
('Granit Xhaka',       (select id from public.selecoes where codigo='SUI')),
('Remo Freuler',       (select id from public.selecoes where codigo='SUI')),
('Denis Zakaria',      (select id from public.selecoes where codigo='SUI')),
('Xherdan Shaqiri',    (select id from public.selecoes where codigo='SUI')),
('Steven Zuber',       (select id from public.selecoes where codigo='SUI')),
('Ruben Vargas',       (select id from public.selecoes where codigo='SUI')),
('Fabian Rieder',      (select id from public.selecoes where codigo='SUI')),
('Breel Embolo',       (select id from public.selecoes where codigo='SUI')),
('Haris Seferovic',    (select id from public.selecoes where codigo='SUI')),
('Noah Okafor',        (select id from public.selecoes where codigo='SUI')),
('Dan Ndoye',          (select id from public.selecoes where codigo='SUI')),
('Zeki Amdouni',       (select id from public.selecoes where codigo='SUI')),
('Ardon Jashari',      (select id from public.selecoes where codigo='SUI')),
('Michel Aebischer',   (select id from public.selecoes where codigo='SUI')),

-- Grupo B: QAT
('Meshaal Barsham',    (select id from public.selecoes where codigo='QAT')),
('Saad Al Sheeb',      (select id from public.selecoes where codigo='QAT')),
('Yousuf Hassan',      (select id from public.selecoes where codigo='QAT')),
('Bassam Al Rawi',     (select id from public.selecoes where codigo='QAT')),
('Tarek Salman',       (select id from public.selecoes where codigo='QAT')),
('Abdelkarim Hassan',  (select id from public.selecoes where codigo='QAT')),
('Pedro Miguel',       (select id from public.selecoes where codigo='QAT')),
('Boualem Khoukhi',    (select id from public.selecoes where codigo='QAT')),
('Musab Kheder',       (select id from public.selecoes where codigo='QAT')),
('Karim Boudiaf',      (select id from public.selecoes where codigo='QAT')),
('Abdulaziz Hatem',    (select id from public.selecoes where codigo='QAT')),
('Salem Al-Hajri',     (select id from public.selecoes where codigo='QAT')),
('Mohammed Waad',      (select id from public.selecoes where codigo='QAT')),
('Assim Madibo',       (select id from public.selecoes where codigo='QAT')),
('Ali Asad',           (select id from public.selecoes where codigo='QAT')),
('Ahmad Fathi',        (select id from public.selecoes where codigo='QAT')),
('Akram Afif',         (select id from public.selecoes where codigo='QAT')),
('Almoez Ali',         (select id from public.selecoes where codigo='QAT')),
('Hassan Al-Haydos',   (select id from public.selecoes where codigo='QAT')),
('Mohammed Muntari',   (select id from public.selecoes where codigo='QAT')),
('Khalid Muneer',      (select id from public.selecoes where codigo='QAT')),
('Ismaeel Al-Hammadi', (select id from public.selecoes where codigo='QAT')),
('Yusuf Abdurisag',    (select id from public.selecoes where codigo='QAT')),

-- Grupo B: BIH
('Ibrahim Sehic',      (select id from public.selecoes where codigo='BIH')),
('Nikola Vasilj',      (select id from public.selecoes where codigo='BIH')),
('Kenan Piric',        (select id from public.selecoes where codigo='BIH')),
('Sead Kolasinac',     (select id from public.selecoes where codigo='BIH')),
('Anel Ahmedhodzic',   (select id from public.selecoes where codigo='BIH')),
('Ermin Bicakcic',     (select id from public.selecoes where codigo='BIH')),
('Amar Dedic',         (select id from public.selecoes where codigo='BIH')),
('Dario Saric',        (select id from public.selecoes where codigo='BIH')),
('Muhamed Mujakic',    (select id from public.selecoes where codigo='BIH')),
('Haris Hajradinovic', (select id from public.selecoes where codigo='BIH')),
('Miralem Pjanic',     (select id from public.selecoes where codigo='BIH')),
('Sead Hadzic',        (select id from public.selecoes where codigo='BIH')),
('Amer Gojak',         (select id from public.selecoes where codigo='BIH')),
('Darko Todorovic',    (select id from public.selecoes where codigo='BIH')),
('Ermedin Demirovic',  (select id from public.selecoes where codigo='BIH')),
('Edin Dzeko',         (select id from public.selecoes where codigo='BIH')),
('Armin Hodzic',       (select id from public.selecoes where codigo='BIH')),
('Luka Menalo',        (select id from public.selecoes where codigo='BIH')),
('Muhamed Besic',      (select id from public.selecoes where codigo='BIH')),
('Tarik Tissoudali',   (select id from public.selecoes where codigo='BIH')),
('Denis Huseinbasic',  (select id from public.selecoes where codigo='BIH')),
('Neven Djuric',       (select id from public.selecoes where codigo='BIH')),
('Jusuf Gazibegovic',  (select id from public.selecoes where codigo='BIH')),

-- Grupo C: BRA
('Alisson',            (select id from public.selecoes where codigo='BRA')),
('Ederson',            (select id from public.selecoes where codigo='BRA')),
('Weverton',           (select id from public.selecoes where codigo='BRA')),
('Marquinhos',         (select id from public.selecoes where codigo='BRA')),
('Gabriel Magalhães',  (select id from public.selecoes where codigo='BRA')),
('Bremer',             (select id from public.selecoes where codigo='BRA')),
('Danilo',             (select id from public.selecoes where codigo='BRA')),
('Alex Sandro',        (select id from public.selecoes where codigo='BRA')),
('Casemiro',           (select id from public.selecoes where codigo='BRA')),
('Bruno Guimarães',    (select id from public.selecoes where codigo='BRA')),
('Fabinho',            (select id from public.selecoes where codigo='BRA')),
('Lucas Paquetá',      (select id from public.selecoes where codigo='BRA')),
('Vinícius Júnior',    (select id from public.selecoes where codigo='BRA')),
('Raphinha',           (select id from public.selecoes where codigo='BRA')),
('Neymar',             (select id from public.selecoes where codigo='BRA')),
('Rodrygo',            (select id from public.selecoes where codigo='BRA')),
('Gabriel Martinelli', (select id from public.selecoes where codigo='BRA')),
('Endrick',            (select id from public.selecoes where codigo='BRA')),
('Matheus Cunha',      (select id from public.selecoes where codigo='BRA')),
('Igor Thiago',        (select id from public.selecoes where codigo='BRA')),
('Luiz Henrique',      (select id from public.selecoes where codigo='BRA')),
('Rayan',              (select id from public.selecoes where codigo='BRA')),
('Savinho',            (select id from public.selecoes where codigo='BRA')),

-- Grupo C: MAR
('Yassine Bounou',     (select id from public.selecoes where codigo='MAR')),
('Ahmed Reda Tagnaouti',(select id from public.selecoes where codigo='MAR')),
('Munir Mohamedi',     (select id from public.selecoes where codigo='MAR')),
('Achraf Hakimi',      (select id from public.selecoes where codigo='MAR')),
('Noussair Mazraoui',  (select id from public.selecoes where codigo='MAR')),
('Romain Saiss',       (select id from public.selecoes where codigo='MAR')),
('Nayef Aguerd',       (select id from public.selecoes where codigo='MAR')),
('Jawad El Yamiq',     (select id from public.selecoes where codigo='MAR')),
('Adam Masina',        (select id from public.selecoes where codigo='MAR')),
('Selim Amallah',      (select id from public.selecoes where codigo='MAR')),
('Sofyan Amrabat',     (select id from public.selecoes where codigo='MAR')),
('Azzedine Ounahi',    (select id from public.selecoes where codigo='MAR')),
('Bilal El Khannouss', (select id from public.selecoes where codigo='MAR')),
('Ilias Chair',        (select id from public.selecoes where codigo='MAR')),
('Hakim Ziyech',       (select id from public.selecoes where codigo='MAR')),
('Youssef En-Nesyri',  (select id from public.selecoes where codigo='MAR')),
('Soufiane Rahimi',    (select id from public.selecoes where codigo='MAR')),
('Abde Ezzalzouli',    (select id from public.selecoes where codigo='MAR')),
('Munir El Haddadi',   (select id from public.selecoes where codigo='MAR')),
('Walid Cheddira',     (select id from public.selecoes where codigo='MAR')),
('Zakaria Aboukhlal',  (select id from public.selecoes where codigo='MAR')),
('Anass Zaroury',      (select id from public.selecoes where codigo='MAR')),
('Ayoub El Kaabi',     (select id from public.selecoes where codigo='MAR')),

-- Grupo C: HAI
('Josué Duverger',     (select id from public.selecoes where codigo='HAI')),
('Herve Placide',      (select id from public.selecoes where codigo='HAI')),
('Yves Romain',        (select id from public.selecoes where codigo='HAI')),
('Derrick Etienne',    (select id from public.selecoes where codigo='HAI')),
('Frantzdy Pierrot',   (select id from public.selecoes where codigo='HAI')),
('Andrew Jean-Baptiste',(select id from public.selecoes where codigo='HAI')),
('Mechack Jerome',     (select id from public.selecoes where codigo='HAI')),
('Kervens Belfort',    (select id from public.selecoes where codigo='HAI')),
('Herby Fortunat',     (select id from public.selecoes where codigo='HAI')),
('Carlens Arcus',      (select id from public.selecoes where codigo='HAI')),
('Nicolas Janvier',    (select id from public.selecoes where codigo='HAI')),
('Jeff Louis',         (select id from public.selecoes where codigo='HAI')),
('Duckens Nazon',      (select id from public.selecoes where codigo='HAI')),
('Kevin Lafrance',     (select id from public.selecoes where codigo='HAI')),
('Ricard Richardson',  (select id from public.selecoes where codigo='HAI')),
('Dominique Badji',    (select id from public.selecoes where codigo='HAI')),
('Wilde Donald Guerrier',(select id from public.selecoes where codigo='HAI')),
('Woodenski Taclet',   (select id from public.selecoes where codigo='HAI')),
('Moise Salaun',       (select id from public.selecoes where codigo='HAI')),
('Daniel Simon',       (select id from public.selecoes where codigo='HAI')),
('Steeven Saba',       (select id from public.selecoes where codigo='HAI')),
('James Bellegarde',   (select id from public.selecoes where codigo='HAI')),
('Ronaldo Damus',      (select id from public.selecoes where codigo='HAI')),

-- Grupo C: SCO
('Angus Gunn',         (select id from public.selecoes where codigo='SCO')),
('Craig Gordon',       (select id from public.selecoes where codigo='SCO')),
('Liam Kelly',         (select id from public.selecoes where codigo='SCO')),
('Grant Hanley',       (select id from public.selecoes where codigo='SCO')),
('Scott McKenna',      (select id from public.selecoes where codigo='SCO')),
('Ryan Porteous',      (select id from public.selecoes where codigo='SCO')),
('Andy Robertson',     (select id from public.selecoes where codigo='SCO')),
('Aaron Hickey',       (select id from public.selecoes where codigo='SCO')),
('Nathan Patterson',   (select id from public.selecoes where codigo='SCO')),
('John Souttar',       (select id from public.selecoes where codigo='SCO')),
('Kieran Tierney',     (select id from public.selecoes where codigo='SCO')),
('Scott McTominay',    (select id from public.selecoes where codigo='SCO')),
('John McGinn',        (select id from public.selecoes where codigo='SCO')),
('Ryan Jack',          (select id from public.selecoes where codigo='SCO')),
('Billy Gilmour',      (select id from public.selecoes where codigo='SCO')),
('Stuart Armstrong',   (select id from public.selecoes where codigo='SCO')),
('Kenny McLean',       (select id from public.selecoes where codigo='SCO')),
('Ryan Christie',      (select id from public.selecoes where codigo='SCO')),
('Che Adams',          (select id from public.selecoes where codigo='SCO')),
('Lyndon Dykes',       (select id from public.selecoes where codigo='SCO')),
('Lawrence Shankland', (select id from public.selecoes where codigo='SCO')),
('Callum McGregor',    (select id from public.selecoes where codigo='SCO')),
('Jack Hendry',        (select id from public.selecoes where codigo='SCO')),

-- Grupo D: USA
('Matt Turner',        (select id from public.selecoes where codigo='USA')),
('Ethan Horvath',      (select id from public.selecoes where codigo='USA')),
('Sean Johnson',       (select id from public.selecoes where codigo='USA')),
('Sergiño Dest',       (select id from public.selecoes where codigo='USA')),
('Tim Ream',           (select id from public.selecoes where codigo='USA')),
('Miles Robinson',     (select id from public.selecoes where codigo='USA')),
('Chris Richards',     (select id from public.selecoes where codigo='USA')),
('Walker Zimmerman',   (select id from public.selecoes where codigo='USA')),
('Antonee Robinson',   (select id from public.selecoes where codigo='USA')),
('Joe Scally',         (select id from public.selecoes where codigo='USA')),
('Tyler Adams',        (select id from public.selecoes where codigo='USA')),
('Weston McKennie',    (select id from public.selecoes where codigo='USA')),
('Yunus Musah',        (select id from public.selecoes where codigo='USA')),
('Gio Reyna',          (select id from public.selecoes where codigo='USA')),
('Christian Pulisic',  (select id from public.selecoes where codigo='USA')),
('Timothy Weah',       (select id from public.selecoes where codigo='USA')),
('Brenden Aaronson',   (select id from public.selecoes where codigo='USA')),
('Folarin Balogun',    (select id from public.selecoes where codigo='USA')),
('Ricardo Pepi',       (select id from public.selecoes where codigo='USA')),
('Josh Sargent',       (select id from public.selecoes where codigo='USA')),
('Jordan Morris',      (select id from public.selecoes where codigo='USA')),
('Malik Tillman',      (select id from public.selecoes where codigo='USA')),
('Luca de la Torre',   (select id from public.selecoes where codigo='USA')),

-- Grupo D: PAR
('Antony Silva',       (select id from public.selecoes where codigo='PAR')),
('Alex Fernandez',     (select id from public.selecoes where codigo='PAR')),
('Alfredo Aguilar',    (select id from public.selecoes where codigo='PAR')),
('Junior Alonso',      (select id from public.selecoes where codigo='PAR')),
('Omar Alderete',      (select id from public.selecoes where codigo='PAR')),
('Santiago Arzamendia',(select id from public.selecoes where codigo='PAR')),
('Robert Rojas',       (select id from public.selecoes where codigo='PAR')),
('Fabian Balbuena',    (select id from public.selecoes where codigo='PAR')),
('Nicolas Otamendi',   (select id from public.selecoes where codigo='PAR')),
('Gustavo Gomez',      (select id from public.selecoes where codigo='PAR')),
('Mathias Villasanti', (select id from public.selecoes where codigo='PAR')),
('Richard Sanchez',    (select id from public.selecoes where codigo='PAR')),
('Andres Cubas',       (select id from public.selecoes where codigo='PAR')),
('Rodrigo Rojas',      (select id from public.selecoes where codigo='PAR')),
('Miguel Almiron',     (select id from public.selecoes where codigo='PAR')),
('Julio Enciso',       (select id from public.selecoes where codigo='PAR')),
('Braian Ojeda',       (select id from public.selecoes where codigo='PAR')),
('Antonio Sanabria',   (select id from public.selecoes where codigo='PAR')),
('Alexis Duarte',      (select id from public.selecoes where codigo='PAR')),
('Angel Romero',       (select id from public.selecoes where codigo='PAR')),
('Ruben Sanchez',      (select id from public.selecoes where codigo='PAR')),
('Jorge Morel',        (select id from public.selecoes where codigo='PAR')),
('Jesus Medina',       (select id from public.selecoes where codigo='PAR')),

-- Grupo D: AUS
('Mathew Ryan',        (select id from public.selecoes where codigo='AUS')),
('Danny Vukovic',      (select id from public.selecoes where codigo='AUS')),
('Andrew Redmayne',    (select id from public.selecoes where codigo='AUS')),
('Milos Degenek',      (select id from public.selecoes where codigo='AUS')),
('Harry Souttar',      (select id from public.selecoes where codigo='AUS')),
('Rhyan Grant',        (select id from public.selecoes where codigo='AUS')),
('Thomas Deng',        (select id from public.selecoes where codigo='AUS')),
('Joel King',          (select id from public.selecoes where codigo='AUS')),
('Aziz Behich',        (select id from public.selecoes where codigo='AUS')),
('Kye Rowles',         (select id from public.selecoes where codigo='AUS')),
('Aaron Mooy',         (select id from public.selecoes where codigo='AUS')),
('Jackson Irvine',     (select id from public.selecoes where codigo='AUS')),
('Ajdin Hrustic',      (select id from public.selecoes where codigo='AUS')),
('Riley McGree',       (select id from public.selecoes where codigo='AUS')),
('Tom Rogic',          (select id from public.selecoes where codigo='AUS')),
('Mathew Leckie',      (select id from public.selecoes where codigo='AUS')),
('Martin Boyle',       (select id from public.selecoes where codigo='AUS')),
('Craig Goodwin',      (select id from public.selecoes where codigo='AUS')),
('Awer Mabil',         (select id from public.selecoes where codigo='AUS')),
('Garang Kuol',        (select id from public.selecoes where codigo='AUS')),
('Mitchell Duke',      (select id from public.selecoes where codigo='AUS')),
('Adam Taggart',       (select id from public.selecoes where codigo='AUS')),
('Kusini Yengi',       (select id from public.selecoes where codigo='AUS')),

-- Grupo D: TUR
('Altay Bayindir',     (select id from public.selecoes where codigo='TUR')),
('Mert Gunok',         (select id from public.selecoes where codigo='TUR')),
('Ugurcan Cakir',      (select id from public.selecoes where codigo='TUR')),
('Merih Demiral',      (select id from public.selecoes where codigo='TUR')),
('Zeki Celik',         (select id from public.selecoes where codigo='TUR')),
('Ozan Kabak',         (select id from public.selecoes where codigo='TUR')),
('Ferdi Kadioglu',     (select id from public.selecoes where codigo='TUR')),
('Mert Muldur',        (select id from public.selecoes where codigo='TUR')),
('Ahmet Calik',        (select id from public.selecoes where codigo='TUR')),
('Samet Akaydin',      (select id from public.selecoes where codigo='TUR')),
('Hakan Calhanoglu',   (select id from public.selecoes where codigo='TUR')),
('Salih Ozcan',        (select id from public.selecoes where codigo='TUR')),
('Okay Yokuslu',       (select id from public.selecoes where codigo='TUR')),
('Orkun Kokcu',        (select id from public.selecoes where codigo='TUR')),
('Arda Guler',         (select id from public.selecoes where codigo='TUR')),
('Kenan Yildiz',       (select id from public.selecoes where codigo='TUR')),
('Baris Alper Yilmaz', (select id from public.selecoes where codigo='TUR')),
('Yusuf Yazici',       (select id from public.selecoes where codigo='TUR')),
('Umut Nayir',         (select id from public.selecoes where codigo='TUR')),
('Cenk Tosun',         (select id from public.selecoes where codigo='TUR')),
('Burak Yilmaz',       (select id from public.selecoes where codigo='TUR')),
('Abdulkadir Omur',    (select id from public.selecoes where codigo='TUR')),
('Muhammed Sengezer',  (select id from public.selecoes where codigo='TUR')),

-- Grupo E: GER
('Manuel Neuer',       (select id from public.selecoes where codigo='GER')),
('Marc-Andre ter Stegen',(select id from public.selecoes where codigo='GER')),
('Oliver Baumann',     (select id from public.selecoes where codigo='GER')),
('Antonio Rudiger',    (select id from public.selecoes where codigo='GER')),
('Niklas Sule',        (select id from public.selecoes where codigo='GER')),
('Matthias Ginter',    (select id from public.selecoes where codigo='GER')),
('Nico Schlotterbeck', (select id from public.selecoes where codigo='GER')),
('David Raum',         (select id from public.selecoes where codigo='GER')),
('Joshua Kimmich',     (select id from public.selecoes where codigo='GER')),
('Leon Goretzka',      (select id from public.selecoes where codigo='GER')),
('Ilkay Gundogan',     (select id from public.selecoes where codigo='GER')),
('Kai Havertz',        (select id from public.selecoes where codigo='GER')),
('Florian Wirtz',      (select id from public.selecoes where codigo='GER')),
('Jamal Musiala',      (select id from public.selecoes where codigo='GER')),
('Thomas Muller',      (select id from public.selecoes where codigo='GER')),
('Leroy Sane',         (select id from public.selecoes where codigo='GER')),
('Serge Gnabry',       (select id from public.selecoes where codigo='GER')),
('Karim Adeyemi',      (select id from public.selecoes where codigo='GER')),
('Niclas Fullkrug',    (select id from public.selecoes where codigo='GER')),
('Deniz Undav',        (select id from public.selecoes where codigo='GER')),
('Maximilian Beier',   (select id from public.selecoes where codigo='GER')),
('Pascal Gross',       (select id from public.selecoes where codigo='GER')),
('Alexander Nubel',    (select id from public.selecoes where codigo='GER')),

-- Grupo E: CUW
('Eloy Room',          (select id from public.selecoes where codigo='CUW')),
('Cody Gakpo',         (select id from public.selecoes where codigo='CUW')),
('Leandro Bacuna',     (select id from public.selecoes where codigo='CUW')),
('Juninho Bacuna',     (select id from public.selecoes where codigo='CUW')),
('Riechedly Bazoer',   (select id from public.selecoes where codigo='CUW')),
('Rangelo Janga',      (select id from public.selecoes where codigo='CUW')),
('Giliano Wijnaldum',  (select id from public.selecoes where codigo='CUW')),
('Jurien Gaari',       (select id from public.selecoes where codigo='CUW')),
('Ethan Sambo',        (select id from public.selecoes where codigo='CUW')),
('Sheraldo Becker',    (select id from public.selecoes where codigo='CUW')),
('Cuco Martina',       (select id from public.selecoes where codigo='CUW')),
('Quentin Brenet',     (select id from public.selecoes where codigo='CUW')),
('Henrico Drost',      (select id from public.selecoes where codigo='CUW')),
('Mateusz Bogusz',     (select id from public.selecoes where codigo='CUW')),
('Jarchinio Antonia',  (select id from public.selecoes where codigo='CUW')),
('Jair Margaritha',    (select id from public.selecoes where codigo='CUW')),
('Gevaro Nepomuceno',  (select id from public.selecoes where codigo='CUW')),
('Jayden Braaf',       (select id from public.selecoes where codigo='CUW')),
('Eljero Elia',        (select id from public.selecoes where codigo='CUW')),
('Romell Quaita',      (select id from public.selecoes where codigo='CUW')),
('Brandley Kuwas',     (select id from public.selecoes where codigo='CUW')),
('Boy Waterman',       (select id from public.selecoes where codigo='CUW')),
('Darryl Lachman',     (select id from public.selecoes where codigo='CUW')),

-- Grupo E: CIV
('Badra Ali Sangare',  (select id from public.selecoes where codigo='CIV')),
('Yahia Fofana',       (select id from public.selecoes where codigo='CIV')),
('Cheick Doucoure',    (select id from public.selecoes where codigo='CIV')),
('Simon Deli',         (select id from public.selecoes where codigo='CIV')),
('Ghislain Konan',     (select id from public.selecoes where codigo='CIV')),
('Odilon Kossounou',   (select id from public.selecoes where codigo='CIV')),
('Wilfried Zaha',      (select id from public.selecoes where codigo='CIV')),
('Eric Bailly',        (select id from public.selecoes where codigo='CIV')),
('Serge Aurier',       (select id from public.selecoes where codigo='CIV')),
('Franck Kessie',      (select id from public.selecoes where codigo='CIV')),
('Ibrahim Sangare',    (select id from public.selecoes where codigo='CIV')),
('Jean-Michael Seri',  (select id from public.selecoes where codigo='CIV')),
('Seko Fofana',        (select id from public.selecoes where codigo='CIV')),
('Nicolas Pepe',       (select id from public.selecoes where codigo='CIV')),
('Sebastien Haller',   (select id from public.selecoes where codigo='CIV')),
('Wilfried Bony',      (select id from public.selecoes where codigo='CIV')),
('Simon Adingra',      (select id from public.selecoes where codigo='CIV')),
('Oumar Diakite',      (select id from public.selecoes where codigo='CIV')),
('Evan Ndicka',        (select id from public.selecoes where codigo='CIV')),
('Maxwel Cornet',      (select id from public.selecoes where codigo='CIV')),
('Stephy Mavididi',    (select id from public.selecoes where codigo='CIV')),
('Lassina Traore',     (select id from public.selecoes where codigo='CIV')),
('Amad Diallo',        (select id from public.selecoes where codigo='CIV')),

-- Grupo E: ECU
('Hernan Galindez',    (select id from public.selecoes where codigo='ECU')),
('Alexander Dominguez',(select id from public.selecoes where codigo='ECU')),
('Moises Ramon',       (select id from public.selecoes where codigo='ECU')),
('Piero Hincapie',     (select id from public.selecoes where codigo='ECU')),
('Pervis Estupinan',   (select id from public.selecoes where codigo='ECU')),
('Felix Torres',       (select id from public.selecoes where codigo='ECU')),
('Robert Arboleda',    (select id from public.selecoes where codigo='ECU')),
('Angelo Preciado',    (select id from public.selecoes where codigo='ECU')),
('Byron Castillo',     (select id from public.selecoes where codigo='ECU')),
('William Pacho',      (select id from public.selecoes where codigo='ECU')),
('Moises Caicedo',     (select id from public.selecoes where codigo='ECU')),
('Carlos Gruezo',      (select id from public.selecoes where codigo='ECU')),
('Jhegson Mendez',     (select id from public.selecoes where codigo='ECU')),
('Jose Cifuentes',     (select id from public.selecoes where codigo='ECU')),
('Romario Ibarra',     (select id from public.selecoes where codigo='ECU')),
('Jeremy Sarmiento',   (select id from public.selecoes where codigo='ECU')),
('Gonzalo Plata',      (select id from public.selecoes where codigo='ECU')),
('Kevin Rodriguez',    (select id from public.selecoes where codigo='ECU')),
('Jordy Caicedo',      (select id from public.selecoes where codigo='ECU')),
('Djorkaeff Reasco',   (select id from public.selecoes where codigo='ECU')),
('Enner Valencia',     (select id from public.selecoes where codigo='ECU')),
('Michael Estrada',    (select id from public.selecoes where codigo='ECU')),
('Kevin Minda',        (select id from public.selecoes where codigo='ECU')),

-- Grupo F: NED
('Virgil van Dijk',    (select id from public.selecoes where codigo='NED')),
('Frenkie de Jong',    (select id from public.selecoes where codigo='NED')),
('Memphis Depay',      (select id from public.selecoes where codigo='NED')),
('Cody Gakpo',         (select id from public.selecoes where codigo='NED')),
('Andries Noppert',    (select id from public.selecoes where codigo='NED')),
('Mark Flekken',       (select id from public.selecoes where codigo='NED')),
('Bart Verbruggen',    (select id from public.selecoes where codigo='NED')),
('Nathan Ake',         (select id from public.selecoes where codigo='NED')),
('Daley Blind',        (select id from public.selecoes where codigo='NED')),
('Jurrien Timber',     (select id from public.selecoes where codigo='NED')),
('Denzel Dumfries',    (select id from public.selecoes where codigo='NED')),
('Marten de Roon',     (select id from public.selecoes where codigo='NED')),
('Teun Koopmeiners',   (select id from public.selecoes where codigo='NED')),
('Ryan Gravenberch',   (select id from public.selecoes where codigo='NED')),
('Tijjani Reijnders',  (select id from public.selecoes where codigo='NED')),
('Xavi Simons',        (select id from public.selecoes where codigo='NED')),
('Steven Bergwijn',    (select id from public.selecoes where codigo='NED')),
('Wout Weghorst',      (select id from public.selecoes where codigo='NED')),
('Vincent Janssen',    (select id from public.selecoes where codigo='NED')),
('Donyell Malen',      (select id from public.selecoes where codigo='NED')),
('Justin Kluivert',    (select id from public.selecoes where codigo='NED')),
('Lutsharel Geertruida',(select id from public.selecoes where codigo='NED')),
('Brian Brobbey',      (select id from public.selecoes where codigo='NED')),

-- Grupo F: JPN
('Shuichi Gonda',      (select id from public.selecoes where codigo='JPN')),
('Kosei Tani',         (select id from public.selecoes where codigo='JPN')),
('Zion Suzuki',        (select id from public.selecoes where codigo='JPN')),
('Maya Yoshida',       (select id from public.selecoes where codigo='JPN')),
('Ko Itakura',         (select id from public.selecoes where codigo='JPN')),
('Yuto Nagatomo',      (select id from public.selecoes where codigo='JPN')),
('Hiroki Sakai',       (select id from public.selecoes where codigo='JPN')),
('Takehiro Tomiyasu',  (select id from public.selecoes where codigo='JPN')),
('Wataru Endo',        (select id from public.selecoes where codigo='JPN')),
('Hidemasa Morita',    (select id from public.selecoes where codigo='JPN')),
('Gaku Shibasaki',     (select id from public.selecoes where codigo='JPN')),
('Ritsu Doan',         (select id from public.selecoes where codigo='JPN')),
('Junya Ito',          (select id from public.selecoes where codigo='JPN')),
('Kaoru Mitoma',       (select id from public.selecoes where codigo='JPN')),
('Takumi Minamino',    (select id from public.selecoes where codigo='JPN')),
('Ao Tanaka',          (select id from public.selecoes where codigo='JPN')),
('Daichi Kamada',      (select id from public.selecoes where codigo='JPN')),
('Keito Nakamura',     (select id from public.selecoes where codigo='JPN')),
('Takefusa Kubo',      (select id from public.selecoes where codigo='JPN')),
('Ayase Ueda',         (select id from public.selecoes where codigo='JPN')),
('Yoshiki Sugawara',   (select id from public.selecoes where codigo='JPN')),
('Shuto Machino',      (select id from public.selecoes where codigo='JPN')),
('Koki Ogawa',         (select id from public.selecoes where codigo='JPN')),

-- Grupo F: SWE
('Robin Olsen',        (select id from public.selecoes where codigo='SWE')),
('Kristoffer Nordfeldt',(select id from public.selecoes where codigo='SWE')),
('Magnus Wallenberg',  (select id from public.selecoes where codigo='SWE')),
('Victor Lindelof',    (select id from public.selecoes where codigo='SWE')),
('Isak Hien',          (select id from public.selecoes where codigo='SWE')),
('Ludwig Augustinsson',(select id from public.selecoes where codigo='SWE')),
('Marcus Danielson',   (select id from public.selecoes where codigo='SWE')),
('Emil Krafth',        (select id from public.selecoes where codigo='SWE')),
('Carl Starfelt',      (select id from public.selecoes where codigo='SWE')),
('Sebastian Larsson',  (select id from public.selecoes where codigo='SWE')),
('Albin Ekdal',        (select id from public.selecoes where codigo='SWE')),
('Dejan Kulusevski',   (select id from public.selecoes where codigo='SWE')),
('Emil Forsberg',      (select id from public.selecoes where codigo='SWE')),
('Mattias Svanberg',   (select id from public.selecoes where codigo='SWE')),
('Viktor Claesson',    (select id from public.selecoes where codigo='SWE')),
('Robin Quaison',      (select id from public.selecoes where codigo='SWE')),
('Alexander Isak',     (select id from public.selecoes where codigo='SWE')),
('Zlatan Ibrahimovic', (select id from public.selecoes where codigo='SWE')),
('Jordan Larsson',     (select id from public.selecoes where codigo='SWE')),
('Anthony Elanga',     (select id from public.selecoes where codigo='SWE')),
('Viktor Gyokeres',    (select id from public.selecoes where codigo='SWE')),
('Jesper Karlstrom',   (select id from public.selecoes where codigo='SWE')),
('Williot Swedberg',   (select id from public.selecoes where codigo='SWE')),

-- Grupo F: TUN
('Aymen Dahmen',       (select id from public.selecoes where codigo='TUN')),
('Mouez Hassen',       (select id from public.selecoes where codigo='TUN')),
('Bechir Ben Said',    (select id from public.selecoes where codigo='TUN')),
('Montassar Talbi',    (select id from public.selecoes where codigo='TUN')),
('Ali Maaloul',        (select id from public.selecoes where codigo='TUN')),
('Dylan Bronn',        (select id from public.selecoes where codigo='TUN')),
('Yassine Meriah',     (select id from public.selecoes where codigo='TUN')),
('Mohamed Amine Ben Hamida',(select id from public.selecoes where codigo='TUN')),
('Nader Ghandri',      (select id from public.selecoes where codigo='TUN')),
('Ellyes Skhiri',      (select id from public.selecoes where codigo='TUN')),
('Anis Slimane',       (select id from public.selecoes where codigo='TUN')),
('Hannibal Mejbri',    (select id from public.selecoes where codigo='TUN')),
('Ghaylen Chaalali',   (select id from public.selecoes where codigo='TUN')),
('Ferjani Sassi',      (select id from public.selecoes where codigo='TUN')),
('Sabri Lamouchi',     (select id from public.selecoes where codigo='TUN')),
('Youssef Msakni',     (select id from public.selecoes where codigo='TUN')),
('Wahbi Khazri',       (select id from public.selecoes where codigo='TUN')),
('Mohamed Drager',     (select id from public.selecoes where codigo='TUN')),
('Seifeddine Jaziri',  (select id from public.selecoes where codigo='TUN')),
('Issam Jebali',       (select id from public.selecoes where codigo='TUN')),
('Naim Sliti',         (select id from public.selecoes where codigo='TUN')),
('Taha Yassine Khenissi',(select id from public.selecoes where codigo='TUN')),
('Nizar Issaoui',      (select id from public.selecoes where codigo='TUN')),

-- Grupo G: BEL
('Thibaut Courtois',   (select id from public.selecoes where codigo='BEL')),
('Senne Lammens',      (select id from public.selecoes where codigo='BEL')),
('Mike Penders',        (select id from public.selecoes where codigo='BEL')),
('Timothy Castagne',   (select id from public.selecoes where codigo='BEL')),
('Zeno Debast',        (select id from public.selecoes where codigo='BEL')),
('Maxim De Cuyper',    (select id from public.selecoes where codigo='BEL')),
('Koni De Winter',     (select id from public.selecoes where codigo='BEL')),
('Brandon Mechele',    (select id from public.selecoes where codigo='BEL')),
('Thomas Meunier',     (select id from public.selecoes where codigo='BEL')),
('Nathan Ngoy',        (select id from public.selecoes where codigo='BEL')),
('Arthur Theate',      (select id from public.selecoes where codigo='BEL')),
('Kevin De Bruyne',    (select id from public.selecoes where codigo='BEL')),
('Amadou Onana',       (select id from public.selecoes where codigo='BEL')),
('Nicolas Raskin',     (select id from public.selecoes where codigo='BEL')),
('Youri Tielemans',    (select id from public.selecoes where codigo='BEL')),
('Hans Vanaken',       (select id from public.selecoes where codigo='BEL')),
('Axel Witsel',        (select id from public.selecoes where codigo='BEL')),
('Charles De Ketelaere',(select id from public.selecoes where codigo='BEL')),
('Jeremy Doku',        (select id from public.selecoes where codigo='BEL')),
('Alexis Saelemaekers',(select id from public.selecoes where codigo='BEL')),
('Romelu Lukaku',      (select id from public.selecoes where codigo='BEL')),
('Dodi Lukebakio',     (select id from public.selecoes where codigo='BEL')),
('Leandro Trossard',   (select id from public.selecoes where codigo='BEL')),

-- Grupo G: EGY
('Mohamed El Shenawy', (select id from public.selecoes where codigo='EGY')),
('Mostafa Shobeir',    (select id from public.selecoes where codigo='EGY')),
('El Mahdi Soliman',   (select id from public.selecoes where codigo='EGY')),
('Mohamed Abdelmonem', (select id from public.selecoes where codigo='EGY')),
('Hossam Abdelmaguid', (select id from public.selecoes where codigo='EGY')),
('Tarek Hamed',        (select id from public.selecoes where codigo='EGY')),
('Ahmed Hegazi',       (select id from public.selecoes where codigo='EGY')),
('Mohamed Hany',       (select id from public.selecoes where codigo='EGY')),
('Hamdy Fathy',        (select id from public.selecoes where codigo='EGY')),
('Rami Rabia',         (select id from public.selecoes where codigo='EGY')),
('Emam Ashour',        (select id from public.selecoes where codigo='EGY')),
('Nabil Emad',         (select id from public.selecoes where codigo='EGY')),
('Mahmoud Saber',      (select id from public.selecoes where codigo='EGY')),
('Ahmed Zizo',         (select id from public.selecoes where codigo='EGY')),
('Marwan Ateya',       (select id from public.selecoes where codigo='EGY')),
('Mahmoud Trezeguet',  (select id from public.selecoes where codigo='EGY')),
('Mohamed Salah',      (select id from public.selecoes where codigo='EGY')),
('Omar Marmoush',      (select id from public.selecoes where codigo='EGY')),
('Ibrahim Adel',       (select id from public.selecoes where codigo='EGY')),
('Haissem Hassan',     (select id from public.selecoes where codigo='EGY')),
('Mostafa Ziko',       (select id from public.selecoes where codigo='EGY')),
('Mohanad Lasheen',    (select id from public.selecoes where codigo='EGY')),
('Karim Hafez',        (select id from public.selecoes where codigo='EGY')),

-- Grupo G: IRN
('Alireza Beiranvand', (select id from public.selecoes where codigo='IRN')),
('Seyed Hossein Hosseini',(select id from public.selecoes where codigo='IRN')),
('Payam Niazmand',     (select id from public.selecoes where codigo='IRN')),
('Ehsan Hajsafi',      (select id from public.selecoes where codigo='IRN')),
('Milad Mohammadi',    (select id from public.selecoes where codigo='IRN')),
('Shoja Khalilzadeh',  (select id from public.selecoes where codigo='IRN')),
('Rouzbeh Cheshmi',    (select id from public.selecoes where codigo='IRN')),
('Ramin Rezaeian',     (select id from public.selecoes where codigo='IRN')),
('Ali Nemati',         (select id from public.selecoes where codigo='IRN')),
('Saeid Ezatolahi',    (select id from public.selecoes where codigo='IRN')),
('Alireza Jahanbakhsh',(select id from public.selecoes where codigo='IRN')),
('Saman Ghoddos',      (select id from public.selecoes where codigo='IRN')),
('Mohammad Mohebi',    (select id from public.selecoes where codigo='IRN')),
('Mehdi Ghaedi',       (select id from public.selecoes where codigo='IRN')),
('Mehdi Torabi',       (select id from public.selecoes where codigo='IRN')),
('Sardar Azmoun',      (select id from public.selecoes where codigo='IRN')),
('Mehdi Taremi',       (select id from public.selecoes where codigo='IRN')),
('Ali Alipour',        (select id from public.selecoes where codigo='IRN')),
('Amirhossein Hosseinzadeh',(select id from public.selecoes where codigo='IRN')),
('Aria Yousefi',       (select id from public.selecoes where codigo='IRN')),
('Mohammad Ghorbani',  (select id from public.selecoes where codigo='IRN')),
('Dennis Dargahi',     (select id from public.selecoes where codigo='IRN')),
('Shahriar Moghanlou', (select id from public.selecoes where codigo='IRN')),

-- Grupo G: NZL
('Max Crocombe',       (select id from public.selecoes where codigo='NZL')),
('Alex Paulsen',       (select id from public.selecoes where codigo='NZL')),
('Michael Woud',       (select id from public.selecoes where codigo='NZL')),
('Michael Boxall',     (select id from public.selecoes where codigo='NZL')),
('Liberato Cacace',    (select id from public.selecoes where codigo='NZL')),
('Nando Pijnaker',     (select id from public.selecoes where codigo='NZL')),
('Tim Payne',          (select id from public.selecoes where codigo='NZL')),
('Francis De Vries',   (select id from public.selecoes where codigo='NZL')),
('Tommy Smith',        (select id from public.selecoes where codigo='NZL')),
('Tyler Bindon',       (select id from public.selecoes where codigo='NZL')),
('Joe Bell',           (select id from public.selecoes where codigo='NZL')),
('Matt Garbett',       (select id from public.selecoes where codigo='NZL')),
('Marko Stamenic',     (select id from public.selecoes where codigo='NZL')),
('Sarpreet Singh',     (select id from public.selecoes where codigo='NZL')),
('Alex Rufer',         (select id from public.selecoes where codigo='NZL')),
('Ryan Thomas',        (select id from public.selecoes where codigo='NZL')),
('Callan Elliot',      (select id from public.selecoes where codigo='NZL')),
('Chris Wood',         (select id from public.selecoes where codigo='NZL')),
('Kosta Barbarouses',  (select id from public.selecoes where codigo='NZL')),
('Ben Waine',          (select id from public.selecoes where codigo='NZL')),
('Ben Old',            (select id from public.selecoes where codigo='NZL')),
('Callum McCowatt',    (select id from public.selecoes where codigo='NZL')),
('Lachlan Bayliss',    (select id from public.selecoes where codigo='NZL')),

-- Grupo H: ESP
('Unai Simon',         (select id from public.selecoes where codigo='ESP')),
('David Raya',         (select id from public.selecoes where codigo='ESP')),
('Alex Remiro',        (select id from public.selecoes where codigo='ESP')),
('Dani Carvajal',      (select id from public.selecoes where codigo='ESP')),
('Aymeric Laporte',    (select id from public.selecoes where codigo='ESP')),
('Eric Garcia',        (select id from public.selecoes where codigo='ESP')),
('Pau Cubarsi',        (select id from public.selecoes where codigo='ESP')),
('Alejandro Grimaldo', (select id from public.selecoes where codigo='ESP')),
('Marc Cucurella',     (select id from public.selecoes where codigo='ESP')),
('Pedri',              (select id from public.selecoes where codigo='ESP')),
('Gavi',               (select id from public.selecoes where codigo='ESP')),
('Rodri',              (select id from public.selecoes where codigo='ESP')),
('Fabian Ruiz',        (select id from public.selecoes where codigo='ESP')),
('Mikel Merino',       (select id from public.selecoes where codigo='ESP')),
('Martin Zubimendi',   (select id from public.selecoes where codigo='ESP')),
('Lamine Yamal',       (select id from public.selecoes where codigo='ESP')),
('Nico Williams',      (select id from public.selecoes where codigo='ESP')),
('Ferran Torres',      (select id from public.selecoes where codigo='ESP')),
('Dani Olmo',          (select id from public.selecoes where codigo='ESP')),
('Mikel Oyarzabal',    (select id from public.selecoes where codigo='ESP')),
('Alvaro Morata',      (select id from public.selecoes where codigo='ESP')),
('Joselu',             (select id from public.selecoes where codigo='ESP')),
('Ayoze Perez',        (select id from public.selecoes where codigo='ESP')),

-- Grupo H: CPV
('Vozinha',            (select id from public.selecoes where codigo='CPV')),
('Marcio Rosa',        (select id from public.selecoes where codigo='CPV')),
('Kevin Beltrame',     (select id from public.selecoes where codigo='CPV')),
('Roberto Lopes',      (select id from public.selecoes where codigo='CPV')),
('Stopira',            (select id from public.selecoes where codigo='CPV')),
('Dylan Tavares',      (select id from public.selecoes where codigo='CPV')),
('Diney Borges',       (select id from public.selecoes where codigo='CPV')),
('Steven Fortes',      (select id from public.selecoes where codigo='CPV')),
('Willy Semedo',       (select id from public.selecoes where codigo='CPV')),
('Marco Soares',       (select id from public.selecoes where codigo='CPV')),
('Kenny Rocha',        (select id from public.selecoes where codigo='CPV')),
('Jamiro Monteiro',    (select id from public.selecoes where codigo='CPV')),
('Garry Rodrigues',    (select id from public.selecoes where codigo='CPV')),
('Julio Tavares',      (select id from public.selecoes where codigo='CPV')),
('Bryan Teixeira',     (select id from public.selecoes where codigo='CPV')),
('Nuno Tavares',       (select id from public.selecoes where codigo='CPV')),
('Ryan Mendes',        (select id from public.selecoes where codigo='CPV')),
('Amilton Semedo',     (select id from public.selecoes where codigo='CPV')),
('Kevin Pina',         (select id from public.selecoes where codigo='CPV')),
('Patrick Andrade',    (select id from public.selecoes where codigo='CPV')),
('Gilson Benchimol',   (select id from public.selecoes where codigo='CPV')),
('Carlos Dias',        (select id from public.selecoes where codigo='CPV')),
('Kenny Pina',         (select id from public.selecoes where codigo='CPV')),

-- Grupo H: KSA
('Mohammed Al Owais',  (select id from public.selecoes where codigo='KSA')),
('Fawaz Al Qarni',     (select id from public.selecoes where codigo='KSA')),
('Yasser Al Mosailem', (select id from public.selecoes where codigo='KSA')),
('Ali Al Bulaihi',     (select id from public.selecoes where codigo='KSA')),
('Yasser Al Shahrani', (select id from public.selecoes where codigo='KSA')),
('Sultan Al Ghannam',  (select id from public.selecoes where codigo='KSA')),
('Abdulelah Al Amri',  (select id from public.selecoes where codigo='KSA')),
('Hassan Tambakti',    (select id from public.selecoes where codigo='KSA')),
('Saud Abdulhamid',    (select id from public.selecoes where codigo='KSA')),
('Mohammed Al Breik',  (select id from public.selecoes where codigo='KSA')),
('Salman Al Faraj',    (select id from public.selecoes where codigo='KSA')),
('Ali Al Nimer',       (select id from public.selecoes where codigo='KSA')),
('Abdulelah Al Malki', (select id from public.selecoes where codigo='KSA')),
('Sami Al Najei',      (select id from public.selecoes where codigo='KSA')),
('Mohamed Kanno',      (select id from public.selecoes where codigo='KSA')),
('Abdullah Otayf',     (select id from public.selecoes where codigo='KSA')),
('Abdulrahman Al Aboud',(select id from public.selecoes where codigo='KSA')),
('Fahad Al Muwallad',  (select id from public.selecoes where codigo='KSA')),
('Salem Al Dawsari',   (select id from public.selecoes where codigo='KSA')),
('Hattan Bahebri',     (select id from public.selecoes where codigo='KSA')),
('Firas Al Buraikan',  (select id from public.selecoes where codigo='KSA')),
('Saleh Al Shehri',    (select id from public.selecoes where codigo='KSA')),
('Nasser Al Dawsari',  (select id from public.selecoes where codigo='KSA')),

-- Grupo H: URU
('Fernando Muslera',   (select id from public.selecoes where codigo='URU')),
('Sebastian Rochet',   (select id from public.selecoes where codigo='URU')),
('Sergio Rochet',      (select id from public.selecoes where codigo='URU')),
('Jose Gimenez',       (select id from public.selecoes where codigo='URU')),
('Diego Godin',        (select id from public.selecoes where codigo='URU')),
('Ronald Araujo',      (select id from public.selecoes where codigo='URU')),
('Matias Vina',        (select id from public.selecoes where codigo='URU')),
('Martin Caceres',     (select id from public.selecoes where codigo='URU')),
('Nahitan Nandez',     (select id from public.selecoes where codigo='URU')),
('Rodrigo Bentancur',  (select id from public.selecoes where codigo='URU')),
('Federico Valverde',  (select id from public.selecoes where codigo='URU')),
('Manuel Ugarte',      (select id from public.selecoes where codigo='URU')),
('Lucas Torreira',     (select id from public.selecoes where codigo='URU')),
('Mathias Olivera',    (select id from public.selecoes where codigo='URU')),
('Giorgian de Arrascaeta',(select id from public.selecoes where codigo='URU')),
('Nicolas de la Cruz', (select id from public.selecoes where codigo='URU')),
('Facundo Pellistri',  (select id from public.selecoes where codigo='URU')),
('Darwin Nunez',       (select id from public.selecoes where codigo='URU')),
('Luis Suarez',        (select id from public.selecoes where codigo='URU')),
('Edinson Cavani',     (select id from public.selecoes where codigo='URU')),
('Brian Ocampo',       (select id from public.selecoes where codigo='URU')),
('Santiago Bueno',     (select id from public.selecoes where codigo='URU')),
('Agustin Canobbio',   (select id from public.selecoes where codigo='URU')),

-- Grupo I: FRA
('Mike Maignan',       (select id from public.selecoes where codigo='FRA')),
('Alphonse Areola',    (select id from public.selecoes where codigo='FRA')),
('Brice Samba',        (select id from public.selecoes where codigo='FRA')),
('William Saliba',     (select id from public.selecoes where codigo='FRA')),
('Raphael Varane',     (select id from public.selecoes where codigo='FRA')),
('Dayot Upamecano',    (select id from public.selecoes where codigo='FRA')),
('Jules Kounde',       (select id from public.selecoes where codigo='FRA')),
('Ibrahima Konate',    (select id from public.selecoes where codigo='FRA')),
('Theo Hernandez',     (select id from public.selecoes where codigo='FRA')),
('Lucas Hernandez',    (select id from public.selecoes where codigo='FRA')),
('Benjamin Pavard',    (select id from public.selecoes where codigo='FRA')),
('N Golo Kante',       (select id from public.selecoes where codigo='FRA')),
('Aurelien Tchouameni',(select id from public.selecoes where codigo='FRA')),
('Adrien Rabiot',      (select id from public.selecoes where codigo='FRA')),
('Eduardo Camavinga',  (select id from public.selecoes where codigo='FRA')),
('Warren Zaire-Emery', (select id from public.selecoes where codigo='FRA')),
('Kylian Mbappe',      (select id from public.selecoes where codigo='FRA')),
('Ousmane Dembele',    (select id from public.selecoes where codigo='FRA')),
('Marcus Thuram',      (select id from public.selecoes where codigo='FRA')),
('Olivier Giroud',     (select id from public.selecoes where codigo='FRA')),
('Antoine Griezmann',  (select id from public.selecoes where codigo='FRA')),
('Bradley Barcola',    (select id from public.selecoes where codigo='FRA')),
('Michael Olise',      (select id from public.selecoes where codigo='FRA')),

-- Grupo I: SEN
('Edouard Mendy',      (select id from public.selecoes where codigo='SEN')),
('Seny Dieng',         (select id from public.selecoes where codigo='SEN')),
('Alfred Gomis',       (select id from public.selecoes where codigo='SEN')),
('Kalidou Koulibaly',  (select id from public.selecoes where codigo='SEN')),
('Abdou Diallo',       (select id from public.selecoes where codigo='SEN')),
('Formose Mendy',      (select id from public.selecoes where codigo='SEN')),
('Youssouf Sabaly',    (select id from public.selecoes where codigo='SEN')),
('Moussa Niakhate',    (select id from public.selecoes where codigo='SEN')),
('Ismail Jakobs',      (select id from public.selecoes where codigo='SEN')),
('Cheikhou Kouyate',   (select id from public.selecoes where codigo='SEN')),
('Idrissa Gueye',      (select id from public.selecoes where codigo='SEN')),
('Nampalys Mendy',     (select id from public.selecoes where codigo='SEN')),
('Pape Matar Sarr',    (select id from public.selecoes where codigo='SEN')),
('Krepin Diatta',      (select id from public.selecoes where codigo='SEN')),
('Sadio Mane',         (select id from public.selecoes where codigo='SEN')),
('Ismaila Sarr',       (select id from public.selecoes where codigo='SEN')),
('Boulaye Dia',        (select id from public.selecoes where codigo='SEN')),
('Nicolas Jackson',    (select id from public.selecoes where codigo='SEN')),
('Iliman Ndiaye',      (select id from public.selecoes where codigo='SEN')),
('Habib Diallo',       (select id from public.selecoes where codigo='SEN')),
('Lamine Camara',      (select id from public.selecoes where codigo='SEN')),
('Pathé Ciss',         (select id from public.selecoes where codigo='SEN')),
('Fodé Ballo-Touré',   (select id from public.selecoes where codigo='SEN')),

-- Grupo I: NOR
('Orjan Nyland',       (select id from public.selecoes where codigo='NOR')),
('Jorgen Strand Larsen',(select id from public.selecoes where codigo='NOR')),
('Stefan Strandberg',  (select id from public.selecoes where codigo='NOR')),
('Leo Ostigard',       (select id from public.selecoes where codigo='NOR')),
('Kristoffer Ajer',    (select id from public.selecoes where codigo='NOR')),
('Omar Elabdellaoui',  (select id from public.selecoes where codigo='NOR')),
('Fredrik Andre Bjorkan',(select id from public.selecoes where codigo='NOR')),
('Birger Meling',      (select id from public.selecoes where codigo='NOR')),
('Marcus Holmgren Pedersen',(select id from public.selecoes where codigo='NOR')),
('Sander Berge',       (select id from public.selecoes where codigo='NOR')),
('Martin Odegaard',    (select id from public.selecoes where codigo='NOR')),
('Mathias Normann',    (select id from public.selecoes where codigo='NOR')),
('Fredrik Aursnes',    (select id from public.selecoes where codigo='NOR')),
('Morten Thorsby',     (select id from public.selecoes where codigo='NOR')),
('Kristian Thorstvedt',(select id from public.selecoes where codigo='NOR')),
('Antonio Nusa',       (select id from public.selecoes where codigo='NOR')),
('Mohamed Elyounoussi',(select id from public.selecoes where codigo='NOR')),
('Alexander Sorloth',  (select id from public.selecoes where codigo='NOR')),
('Erling Haaland',     (select id from public.selecoes where codigo='NOR')),
('Ole Selvik',         (select id from public.selecoes where codigo='NOR')),
('Andreas Schjelderup',(select id from public.selecoes where codigo='NOR')),
('Jens Hauge',         (select id from public.selecoes where codigo='NOR')),
('Tobias Borge Aasgaard',(select id from public.selecoes where codigo='NOR')),

-- Grupo I: IRQ
('Jalal Hassan',       (select id from public.selecoes where codigo='IRQ')),
('Mohammed Talib',     (select id from public.selecoes where codigo='IRQ')),
('Basil Gorgis',       (select id from public.selecoes where codigo='IRQ')),
('Ali Adnan',          (select id from public.selecoes where codigo='IRQ')),
('Rebin Sulaka',       (select id from public.selecoes where codigo='IRQ')),
('Ahmed Ibrahim',      (select id from public.selecoes where codigo='IRQ')),
('Hussein Ali',        (select id from public.selecoes where codigo='IRQ')),
('Ali Faez',           (select id from public.selecoes where codigo='IRQ')),
('Mustafa Nadhim',     (select id from public.selecoes where codigo='IRQ')),
('Osama Rashid',       (select id from public.selecoes where codigo='IRQ')),
('Saad Abdul Amir',    (select id from public.selecoes where codigo='IRQ')),
('Mohanad Ali',        (select id from public.selecoes where codigo='IRQ')),
('Amjad Attwan',       (select id from public.selecoes where codigo='IRQ')),
('Ahmed Yasin',        (select id from public.selecoes where codigo='IRQ')),
('Yousif Mahmoud',     (select id from public.selecoes where codigo='IRQ')),
('Aymen Hussein',      (select id from public.selecoes where codigo='IRQ')),
('Alaa Abbas',         (select id from public.selecoes where codigo='IRQ')),
('Humam Tariq',        (select id from public.selecoes where codigo='IRQ')),
('Amyn Yahia',         (select id from public.selecoes where codigo='IRQ')),
('Ali Al-Hamadi',      (select id from public.selecoes where codigo='IRQ')),
('Murtadha Al-Janabi', (select id from public.selecoes where codigo='IRQ')),
('Klauber Kayala',     (select id from public.selecoes where codigo='IRQ')),
('Ahmed Yacoub',       (select id from public.selecoes where codigo='IRQ')),

-- Grupo J: ARG
('Emiliano Martinez',  (select id from public.selecoes where codigo='ARG')),
('Franco Armani',      (select id from public.selecoes where codigo='ARG')),
('Geronimo Rulli',     (select id from public.selecoes where codigo='ARG')),
('Lionel Messi',       (select id from public.selecoes where codigo='ARG')),
('Angel Di Maria',     (select id from public.selecoes where codigo='ARG')),
('Rodrigo De Paul',    (select id from public.selecoes where codigo='ARG')),
('Alexis Mac Allister',(select id from public.selecoes where codigo='ARG')),
('Enzo Fernandez',     (select id from public.selecoes where codigo='ARG')),
('Leandro Paredes',    (select id from public.selecoes where codigo='ARG')),
('Nicolas Otamendi',   (select id from public.selecoes where codigo='ARG')),
('Cristian Romero',    (select id from public.selecoes where codigo='ARG')),
('Lisandro Martinez',  (select id from public.selecoes where codigo='ARG')),
('Nahuel Molina',      (select id from public.selecoes where codigo='ARG')),
('Nicolas Tagliafico', (select id from public.selecoes where codigo='ARG')),
('Gonzalo Montiel',    (select id from public.selecoes where codigo='ARG')),
('Valentin Barco',     (select id from public.selecoes where codigo='ARG')),
('Julian Alvarez',     (select id from public.selecoes where codigo='ARG')),
('Lautaro Martinez',   (select id from public.selecoes where codigo='ARG')),
('Paulo Dybala',       (select id from public.selecoes where codigo='ARG')),
('Thiago Almada',      (select id from public.selecoes where codigo='ARG')),
('Nico Paz',           (select id from public.selecoes where codigo='ARG')),
('Exequiel Palacios',  (select id from public.selecoes where codigo='ARG')),
('Giovani Lo Celso',   (select id from public.selecoes where codigo='ARG')),

-- Grupo J: ALG
('Rais M Bolhi',       (select id from public.selecoes where codigo='ALG')),
('Alexandre Oukidja',  (select id from public.selecoes where codigo='ALG')),
('Raed Benkadida',     (select id from public.selecoes where codigo='ALG')),
('Riyad Mahrez',       (select id from public.selecoes where codigo='ALG')),
('Islam Slimani',      (select id from public.selecoes where codigo='ALG')),
('Djamel Benlamri',    (select id from public.selecoes where codigo='ALG')),
('Ramy Bensebaini',    (select id from public.selecoes where codigo='ALG')),
('Aissa Mandi',        (select id from public.selecoes where codigo='ALG')),
('Hossem Aouar',       (select id from public.selecoes where codigo='ALG')),
('Sofiane Feghouli',   (select id from public.selecoes where codigo='ALG')),
('Yacine Brahimi',     (select id from public.selecoes where codigo='ALG')),
('Nabil Bentaleb',     (select id from public.selecoes where codigo='ALG')),
('Adlene Guedioura',   (select id from public.selecoes where codigo='ALG')),
('Said Benrahma',      (select id from public.selecoes where codigo='ALG')),
('Ismail Bennacer',    (select id from public.selecoes where codigo='ALG')),
('Mohamed Amine Amoura',(select id from public.selecoes where codigo='ALG')),
('Andy Delort',        (select id from public.selecoes where codigo='ALG')),
('Youcef Atal',        (select id from public.selecoes where codigo='ALG')),
('Badredine Bouanani', (select id from public.selecoes where codigo='ALG')),
('Farid Boulaya',      (select id from public.selecoes where codigo='ALG')),
('Youcef Belaili',     (select id from public.selecoes where codigo='ALG')),
('Ramiz Zerrouki',     (select id from public.selecoes where codigo='ALG')),
('Adam Ounas',         (select id from public.selecoes where codigo='ALG')),

-- Grupo J: AUT
('Daniel Bachmann',    (select id from public.selecoes where codigo='AUT')),
('Alexander Schlager', (select id from public.selecoes where codigo='AUT')),
('Patrick Pentz',      (select id from public.selecoes where codigo='AUT')),
('David Alaba',        (select id from public.selecoes where codigo='AUT')),
('Stefan Posch',       (select id from public.selecoes where codigo='AUT')),
('Philipp Lienhart',   (select id from public.selecoes where codigo='AUT')),
('Kevin Danso',        (select id from public.selecoes where codigo='AUT')),
('Maximilian Wober',   (select id from public.selecoes where codigo='AUT')),
('Philipp Mwene',      (select id from public.selecoes where codigo='AUT')),
('Marcel Sabitzer',    (select id from public.selecoes where codigo='AUT')),
('Konrad Laimer',      (select id from public.selecoes where codigo='AUT')),
('Nicolas Seiwald',    (select id from public.selecoes where codigo='AUT')),
('Florian Grillitsch', (select id from public.selecoes where codigo='AUT')),
('Xaver Schlager',     (select id from public.selecoes where codigo='AUT')),
('Christoph Baumgartner',(select id from public.selecoes where codigo='AUT')),
('Michael Gregoritsch',(select id from public.selecoes where codigo='AUT')),
('Marko Arnautovic',   (select id from public.selecoes where codigo='AUT')),
('Sasa Kalajdzic',     (select id from public.selecoes where codigo='AUT')),
('Patrick Wimmer',     (select id from public.selecoes where codigo='AUT')),
('Louis Schaub',       (select id from public.selecoes where codigo='AUT')),
('Romano Schmid',      (select id from public.selecoes where codigo='AUT')),
('Karim Adeyemi',      (select id from public.selecoes where codigo='AUT')),
('Alexander Prass',    (select id from public.selecoes where codigo='AUT')),

-- Grupo J: JOR
('Amer Shafi',         (select id from public.selecoes where codigo='JOR')),
('Yahia Abulaila',     (select id from public.selecoes where codigo='JOR')),
('Mohammad Al Wardah', (select id from public.selecoes where codigo='JOR')),
('Baher Abdel Fattah', (select id from public.selecoes where codigo='JOR')),
('Baha Faisal',        (select id from public.selecoes where codigo='JOR')),
('Yazan Al Naimat',    (select id from public.selecoes where codigo='JOR')),
('Ahmad Al Rawabdeh',  (select id from public.selecoes where codigo='JOR')),
('Musa Tamari',        (select id from public.selecoes where codigo='JOR')),
('Ahmad Ibrahim',      (select id from public.selecoes where codigo='JOR')),
('Mousa Al Taamari',   (select id from public.selecoes where codigo='JOR')),
('Mahmoud Al Mardi',   (select id from public.selecoes where codigo='JOR')),
('Hamza Al Dardour',   (select id from public.selecoes where codigo='JOR')),
('Saleh Rateb',        (select id from public.selecoes where codigo='JOR')),
('Yousef Abusuha',     (select id from public.selecoes where codigo='JOR')),
('Ayman Khirfan',      (select id from public.selecoes where codigo='JOR')),
('Ibrahim Saied',      (select id from public.selecoes where codigo='JOR')),
('Abdallah Nasib',     (select id from public.selecoes where codigo='JOR')),
('Oday Dabbagh',       (select id from public.selecoes where codigo='JOR')),
('Zaid Al Rashdan',    (select id from public.selecoes where codigo='JOR')),
('Mohammad Abu Zrayq', (select id from public.selecoes where codigo='JOR')),
('Yazeed Iyad',        (select id from public.selecoes where codigo='JOR')),
('Mutaz Aldandan',     (select id from public.selecoes where codigo='JOR')),
('Amir Al Maqableh',   (select id from public.selecoes where codigo='JOR')),

-- Grupo K: POR
('Diogo Costa',        (select id from public.selecoes where codigo='POR')),
('Rui Patricio',       (select id from public.selecoes where codigo='POR')),
('Jose Sa',            (select id from public.selecoes where codigo='POR')),
('Cristiano Ronaldo',  (select id from public.selecoes where codigo='POR')),
('Bruno Fernandes',    (select id from public.selecoes where codigo='POR')),
('Bernardo Silva',     (select id from public.selecoes where codigo='POR')),
('Joao Felix',         (select id from public.selecoes where codigo='POR')),
('Rafael Leao',        (select id from public.selecoes where codigo='POR')),
('Joao Cancelo',       (select id from public.selecoes where codigo='POR')),
('Ruben Dias',         (select id from public.selecoes where codigo='POR')),
('Pepe',               (select id from public.selecoes where codigo='POR')),
('Nuno Mendes',        (select id from public.selecoes where codigo='POR')),
('Diogo Dalot',        (select id from public.selecoes where codigo='POR')),
('Ruben Neves',        (select id from public.selecoes where codigo='POR')),
('Joao Neves',         (select id from public.selecoes where codigo='POR')),
('Vitinha',            (select id from public.selecoes where codigo='POR')),
('Matheus Nunes',      (select id from public.selecoes where codigo='POR')),
('Otavio',             (select id from public.selecoes where codigo='POR')),
('Goncalo Ramos',      (select id from public.selecoes where codigo='POR')),
('Andre Silva',        (select id from public.selecoes where codigo='POR')),
('Ricardo Horta',      (select id from public.selecoes where codigo='POR')),
('Francisco Conceicao',(select id from public.selecoes where codigo='POR')),
('Inacio',             (select id from public.selecoes where codigo='POR')),

-- Grupo K: UZB
('Utkir Yusupov',      (select id from public.selecoes where codigo='UZB')),
('Eldorbek Sobirov',   (select id from public.selecoes where codigo='UZB')),
('Oybek Abdukhairov',  (select id from public.selecoes where codigo='UZB')),
('Dostonbek Khamdamov',(select id from public.selecoes where codigo='UZB')),
('Jasurbek Yakhshiboev',(select id from public.selecoes where codigo='UZB')),
('Abbosbek Fayzullaev',(select id from public.selecoes where codigo='UZB')),
('Jaloliddin Masharipov',(select id from public.selecoes where codigo='UZB')),
('Otabek Shukurov',    (select id from public.selecoes where codigo='UZB')),
('Rustam Ashurmatov',  (select id from public.selecoes where codigo='UZB')),
('Muhammadkodir Hamrobekov',(select id from public.selecoes where codigo='UZB')),
('Sherzod Nasrullaev', (select id from public.selecoes where codigo='UZB')),
('Eldor Shomurodov',   (select id from public.selecoes where codigo='UZB')),
('Bobir Abdullaev',    (select id from public.selecoes where codigo='UZB')),
('Sanjar Tursunov',    (select id from public.selecoes where codigo='UZB')),
('Sardor Rashidov',    (select id from public.selecoes where codigo='UZB')),
('Islom Kobilov',      (select id from public.selecoes where codigo='UZB')),
('Manuchehr Alijonov', (select id from public.selecoes where codigo='UZB')),
('Alisher Urunov',     (select id from public.selecoes where codigo='UZB')),
('Khurshid Karimov',   (select id from public.selecoes where codigo='UZB')),
('Ilhomjon Hamidov',   (select id from public.selecoes where codigo='UZB')),
('Muhammadali Nematov',(select id from public.selecoes where codigo='UZB')),
('Ulugbek Ganiev',     (select id from public.selecoes where codigo='UZB')),
('Bunyod Ergashev',    (select id from public.selecoes where codigo='UZB')),

-- Grupo K: COL
('David Ospina',       (select id from public.selecoes where codigo='COL')),
('Camilo Vargas',      (select id from public.selecoes where codigo='COL')),
('Alvaro Montero',     (select id from public.selecoes where codigo='COL')),
('Luis Diaz',          (select id from public.selecoes where codigo='COL')),
('James Rodriguez',    (select id from public.selecoes where codigo='COL')),
('Falcao',             (select id from public.selecoes where codigo='COL')),
('Juan Cuadrado',      (select id from public.selecoes where codigo='COL')),
('Davinson Sanchez',   (select id from public.selecoes where codigo='COL')),
('Yerry Mina',         (select id from public.selecoes where codigo='COL')),
('Daniel Munoz',       (select id from public.selecoes where codigo='COL')),
('Johan Mojica',       (select id from public.selecoes where codigo='COL')),
('Wilmar Barrios',     (select id from public.selecoes where codigo='COL')),
('Jhon Lucumi',        (select id from public.selecoes where codigo='COL')),
('Jefferson Lerma',    (select id from public.selecoes where codigo='COL')),
('Mateus Uribe',       (select id from public.selecoes where codigo='COL')),
('Juan Fernando Quintero',(select id from public.selecoes where codigo='COL')),
('Cucho Hernandez',    (select id from public.selecoes where codigo='COL')),
('Rafael Santos Borre',(select id from public.selecoes where codigo='COL')),
('Jhon Duran',         (select id from public.selecoes where codigo='COL')),
('Jader Valencia',     (select id from public.selecoes where codigo='COL')),
('John Cordoba',       (select id from public.selecoes where codigo='COL')),
('Richard Rios',       (select id from public.selecoes where codigo='COL')),
('Jorge Carrascal',    (select id from public.selecoes where codigo='COL')),

-- Grupo K: COD
('Joel Kiassumbua',    (select id from public.selecoes where codigo='COD')),
('Lionel Mpasi',       (select id from public.selecoes where codigo='COD')),
('Denis Onyango',      (select id from public.selecoes where codigo='COD')),
('Chancel Mbemba',     (select id from public.selecoes where codigo='COD')),
('Joris Kayembe',      (select id from public.selecoes where codigo='COD')),
('Arthur Masuaku',     (select id from public.selecoes where codigo='COD')),
('Aaron Wan-Bissaka',  (select id from public.selecoes where codigo='COD')),
('Nathan Zeze',        (select id from public.selecoes where codigo='COD')),
('Christian Luyindama',(select id from public.selecoes where codigo='COD')),
('Marcel Tisserand',   (select id from public.selecoes where codigo='COD')),
('Murgia Kapuadi',     (select id from public.selecoes where codigo='COD')),
('Pierre Kalulu',      (select id from public.selecoes where codigo='COD')),
('Yoane Wissa',        (select id from public.selecoes where codigo='COD')),
('Cedric Bakambu',     (select id from public.selecoes where codigo='COD')),
('Britt Assombalonga',  (select id from public.selecoes where codigo='COD')),
('Emmanuel Leko',      (select id from public.selecoes where codigo='COD')),
('Gaël Kakuta',        (select id from public.selecoes where codigo='COD')),
('Neeskens Kebano',    (select id from public.selecoes where codigo='COD')),
('Theo Bongonda',      (select id from public.selecoes where codigo='COD')),
('Samuel Bastien',     (select id from public.selecoes where codigo='COD')),
('Jonathan Bolingi',   (select id from public.selecoes where codigo='COD')),
('Silas Wissa',        (select id from public.selecoes where codigo='COD')),
('Dieumerci Mbokani',  (select id from public.selecoes where codigo='COD')),

-- Grupo L: ENG
('Jordan Pickford',    (select id from public.selecoes where codigo='ENG')),
('Nick Pope',          (select id from public.selecoes where codigo='ENG')),
('Aaron Ramsdale',     (select id from public.selecoes where codigo='ENG')),
('Harry Kane',         (select id from public.selecoes where codigo='ENG')),
('Jude Bellingham',    (select id from public.selecoes where codigo='ENG')),
('Bukayo Saka',        (select id from public.selecoes where codigo='ENG')),
('Phil Foden',         (select id from public.selecoes where codigo='ENG')),
('Declan Rice',        (select id from public.selecoes where codigo='ENG')),
('Kyle Walker',        (select id from public.selecoes where codigo='ENG')),
('John Stones',        (select id from public.selecoes where codigo='ENG')),
('Luke Shaw',          (select id from public.selecoes where codigo='ENG')),
('Kieran Trippier',    (select id from public.selecoes where codigo='ENG')),
('Reece James',        (select id from public.selecoes where codigo='ENG')),
('Ben White',          (select id from public.selecoes where codigo='ENG')),
('Marc Guehi',         (select id from public.selecoes where codigo='ENG')),
('Harry Maguire',      (select id from public.selecoes where codigo='ENG')),
('Marcus Rashford',    (select id from public.selecoes where codigo='ENG')),
('Raheem Sterling',    (select id from public.selecoes where codigo='ENG')),
('Ollie Watkins',      (select id from public.selecoes where codigo='ENG')),
('Ivan Toney',         (select id from public.selecoes where codigo='ENG')),
('Kobbie Mainoo',      (select id from public.selecoes where codigo='ENG')),
('Eberechi Eze',       (select id from public.selecoes where codigo='ENG')),
('Anthony Gordon',     (select id from public.selecoes where codigo='ENG')),

-- Grupo L: CRO
('Dominik Livakovic',  (select id from public.selecoes where codigo='CRO')),
('Ivo Grbic',          (select id from public.selecoes where codigo='CRO')),
('Nediljko Labrovic',  (select id from public.selecoes where codigo='CRO')),
('Luka Modric',        (select id from public.selecoes where codigo='CRO')),
('Mateo Kovacic',      (select id from public.selecoes where codigo='CRO')),
('Ivan Perisic',       (select id from public.selecoes where codigo='CRO')),
('Andrej Kramaric',    (select id from public.selecoes where codigo='CRO')),
('Josko Gvardiol',     (select id from public.selecoes where codigo='CRO')),
('Marcelo Brozovic',   (select id from public.selecoes where codigo='CRO')),
('Mario Pasalic',      (select id from public.selecoes where codigo='CRO')),
('Nikola Vlasic',      (select id from public.selecoes where codigo='CRO')),
('Dejan Lovren',       (select id from public.selecoes where codigo='CRO')),
('Domagoj Vida',       (select id from public.selecoes where codigo='CRO')),
('Borna Sosa',         (select id from public.selecoes where codigo='CRO')),
('Josip Juranovic',    (select id from public.selecoes where codigo='CRO')),
('Marko Livaja',       (select id from public.selecoes where codigo='CRO')),
('Josip Stanisic',     (select id from public.selecoes where codigo='CRO')),
('Luka Sucic',         (select id from public.selecoes where codigo='CRO')),
('Bruno Petkovic',     (select id from public.selecoes where codigo='CRO')),
('Lovro Majer',        (select id from public.selecoes where codigo='CRO')),
('Ante Budimir',       (select id from public.selecoes where codigo='CRO')),
('Dinamo Musa',        (select id from public.selecoes where codigo='CRO')),
('Martin Baturina',    (select id from public.selecoes where codigo='CRO')),

-- Grupo L: GHA
('Joseph Wollacott',   (select id from public.selecoes where codigo='GHA')),
('Lawrence Ati-Zigi',  (select id from public.selecoes where codigo='GHA')),
('Richard Ofori',      (select id from public.selecoes where codigo='GHA')),
('Thomas Partey',      (select id from public.selecoes where codigo='GHA')),
('Jordan Ayew',        (select id from public.selecoes where codigo='GHA')),
('Mohammed Salisu',    (select id from public.selecoes where codigo='GHA')),
('Daniel Amartey',     (select id from public.selecoes where codigo='GHA')),
('Alexander Djiku',    (select id from public.selecoes where codigo='GHA')),
('Tariq Lamptey',      (select id from public.selecoes where codigo='GHA')),
('Baba Rahman',        (select id from public.selecoes where codigo='GHA')),
('Andy Yiadom',        (select id from public.selecoes where codigo='GHA')),
('Elisha Owusu',       (select id from public.selecoes where codigo='GHA')),
('Iddrisu Baba',       (select id from public.selecoes where codigo='GHA')),
('Mohammed Kudus',     (select id from public.selecoes where codigo='GHA')),
('Kamaldeen Sulemana', (select id from public.selecoes where codigo='GHA')),
('Antoine Semenyo',    (select id from public.selecoes where codigo='GHA')),
('Inaki Williams',     (select id from public.selecoes where codigo='GHA')),
('Osman Bukari',       (select id from public.selecoes where codigo='GHA')),
('Felix Afena-Gyan',   (select id from public.selecoes where codigo='GHA')),
('Benjamin Tetteh',    (select id from public.selecoes where codigo='GHA')),
('Richmond Boakye',    (select id from public.selecoes where codigo='GHA')),
('Abdul Fatawu',       (select id from public.selecoes where codigo='GHA')),
('Ernest Nuamah',      (select id from public.selecoes where codigo='GHA')),

-- Grupo L: PAN
('Luis Mejia',         (select id from public.selecoes where codigo='PAN')),
('Jose Calderon',      (select id from public.selecoes where codigo='PAN')),
('Orlando Mosquera',   (select id from public.selecoes where codigo='PAN')),
('Fidel Escobar',      (select id from public.selecoes where codigo='PAN')),
('Eric Davis',         (select id from public.selecoes where codigo='PAN')),
('Jesus Murillo',      (select id from public.selecoes where codigo='PAN')),
('Andres Andrade',     (select id from public.selecoes where codigo='PAN')),
('Harold Cummings',    (select id from public.selecoes where codigo='PAN')),
('Michael Murillo',    (select id from public.selecoes where codigo='PAN')),
('Cesar Blackman',     (select id from public.selecoes where codigo='PAN')),
('Roderick Miller',    (select id from public.selecoes where codigo='PAN')),
('Jose Fajardo',       (select id from public.selecoes where codigo='PAN')),
('Adalberto Carrasquilla',(select id from public.selecoes where codigo='PAN')),
('Andres Godoy',       (select id from public.selecoes where codigo='PAN')),
('Anibal Godoy',       (select id from public.selecoes where codigo='PAN')),
('Edgar Barcenas',     (select id from public.selecoes where codigo='PAN')),
('Rolando Blackburn',  (select id from public.selecoes where codigo='PAN')),
('Alfredo Stephens',   (select id from public.selecoes where codigo='PAN')),
('Ismael Diaz',        (select id from public.selecoes where codigo='PAN')),
('Frederico Piovaccari',(select id from public.selecoes where codigo='PAN')),
('Gabriel Torres',     (select id from public.selecoes where codigo='PAN')),
('Roman Torres',       (select id from public.selecoes where codigo='PAN')),
('Alberto Quintero',   (select id from public.selecoes where codigo='PAN'));

commit;
