-- =====================================================================
-- BolãoEEL — Jogadores candidatos a artilheiro (Copa do Mundo 2026)
-- Atacantes e meias ofensivos dos elencos FINAIS de 26 jogadores,
-- submetidos à FIFA em 01/06/2026.
-- Fonte: Wikipedia "2026 FIFA World Cup squads" (rosters oficiais).
-- Substitui o seed anterior, que continha jogadores aposentados/desatualizados
-- (ex.: Ibrahimović, Cavani, Suárez, Varane, Hutchinson, etc.).
-- Idempotente: pode rodar mais de uma vez.
-- Execute DEPOIS de migration_copa2026.sql.
-- =====================================================================

begin;

-- Tabela (caso ainda não exista)
create table if not exists public.jogadores (
  id         uuid primary key default gen_random_uuid(),
  nome       text not null,
  selecao_id uuid not null references public.selecoes(id) on delete cascade
);
create index if not exists jogadores_selecao_id_idx on public.jogadores(selecao_id);

-- RLS
alter table public.jogadores enable row level security;
drop policy if exists "leitura publica" on public.jogadores;
create policy "leitura publica" on public.jogadores
  for select using (true);

-- Limpa seed anterior para ser idempotente
delete from public.jogadores;

-- =====================================================================
-- SEED: candidatos a artilheiro por seleção (atacantes + meias ofensivos)
-- =====================================================================
insert into public.jogadores (nome, selecao_id) values

-- Grupo A: MEX (Mexico)
('Érik Lira', (select id from public.selecoes where codigo='MEX')),
('Luis Romo', (select id from public.selecoes where codigo='MEX')),
('Álvaro Fidalgo', (select id from public.selecoes where codigo='MEX')),
('Raúl Jiménez', (select id from public.selecoes where codigo='MEX')),
('Alexis Vega', (select id from public.selecoes where codigo='MEX')),
('Santiago Giménez', (select id from public.selecoes where codigo='MEX')),
('Armando González', (select id from public.selecoes where codigo='MEX')),
('Julián Quiñones', (select id from public.selecoes where codigo='MEX')),
('Orbelín Pineda', (select id from public.selecoes where codigo='MEX')),
('Obed Vargas', (select id from public.selecoes where codigo='MEX')),
('Gilberto Mora', (select id from public.selecoes where codigo='MEX')),
('César Huerta', (select id from public.selecoes where codigo='MEX')),
('Guillermo Martínez', (select id from public.selecoes where codigo='MEX')),
('Luis Chávez', (select id from public.selecoes where codigo='MEX')),
('Roberto Alvarado', (select id from public.selecoes where codigo='MEX')),
('Brian Gutiérrez', (select id from public.selecoes where codigo='MEX')),

-- Grupo A: RSA (South Africa)
('Teboho Mokoena', (select id from public.selecoes where codigo='RSA')),
('Thalente Mbatha', (select id from public.selecoes where codigo='RSA')),
('Oswin Appollis', (select id from public.selecoes where codigo='RSA')),
('Tshepang Moremi', (select id from public.selecoes where codigo='RSA')),
('Lyle Foster', (select id from public.selecoes where codigo='RSA')),
('Relebohile Mofokeng', (select id from public.selecoes where codigo='RSA')),
('Themba Zwane', (select id from public.selecoes where codigo='RSA')),
('Thapelo Maseko', (select id from public.selecoes where codigo='RSA')),
('Sphephelo Sithole', (select id from public.selecoes where codigo='RSA')),
('Iqraam Rayners', (select id from public.selecoes where codigo='RSA')),
('Evidence Makgopa', (select id from public.selecoes where codigo='RSA')),
('Jayden Adams', (select id from public.selecoes where codigo='RSA')),
('Kamogelo Sebelebele', (select id from public.selecoes where codigo='RSA')),

-- Grupo A: KOR (South Korea)
('Lee Gi-hyuk', (select id from public.selecoes where codigo='KOR')),
('Hwang In-beom', (select id from public.selecoes where codigo='KOR')),
('Son Heung-min', (select id from public.selecoes where codigo='KOR')),
('Paik Seung-ho', (select id from public.selecoes where codigo='KOR')),
('Cho Gue-sung', (select id from public.selecoes where codigo='KOR')),
('Lee Jae-sung', (select id from public.selecoes where codigo='KOR')),
('Hwang Hee-chan', (select id from public.selecoes where codigo='KOR')),
('Bae Jun-ho', (select id from public.selecoes where codigo='KOR')),
('Oh Hyeon-gyu', (select id from public.selecoes where codigo='KOR')),
('Lee Kang-in', (select id from public.selecoes where codigo='KOR')),
('Yang Hyun-jun', (select id from public.selecoes where codigo='KOR')),
('Kim Jin-gyu', (select id from public.selecoes where codigo='KOR')),
('Eom Ji-sung', (select id from public.selecoes where codigo='KOR')),
('Lee Dong-gyeong', (select id from public.selecoes where codigo='KOR')),

-- Grupo A: CZE (Czech Republic)
('Vladimír Darida', (select id from public.selecoes where codigo='CZE')),
('Adam Hložek', (select id from public.selecoes where codigo='CZE')),
('Patrik Schick', (select id from public.selecoes where codigo='CZE')),
('Jan Kuchta', (select id from public.selecoes where codigo='CZE')),
('Lukáš Červ', (select id from public.selecoes where codigo='CZE')),
('Mojmír Chytil', (select id from public.selecoes where codigo='CZE')),
('Pavel Šulc', (select id from public.selecoes where codigo='CZE')),
('Lukáš Provod', (select id from public.selecoes where codigo='CZE')),
('Michal Sadílek', (select id from public.selecoes where codigo='CZE')),
('Tomáš Chorý', (select id from public.selecoes where codigo='CZE')),
('Tomáš Souček', (select id from public.selecoes where codigo='CZE')),
('Alexandr Sojka', (select id from public.selecoes where codigo='CZE')),
('Hugo Sochůrek', (select id from public.selecoes where codigo='CZE')),
('Denis Višinský', (select id from public.selecoes where codigo='CZE')),

-- Grupo B: CAN (Canada)
('Mathieu Choinière', (select id from public.selecoes where codigo='CAN')),
('Stephen Eustáquio', (select id from public.selecoes where codigo='CAN')),
('Ismaël Koné', (select id from public.selecoes where codigo='CAN')),
('Cyle Larin', (select id from public.selecoes where codigo='CAN')),
('Jonathan David', (select id from public.selecoes where codigo='CAN')),
('Liam Millar', (select id from public.selecoes where codigo='CAN')),
('Tani Oluwaseyi', (select id from public.selecoes where codigo='CAN')),
('Jacob Shaffelburg', (select id from public.selecoes where codigo='CAN')),
('Tajon Buchanan', (select id from public.selecoes where codigo='CAN')),
('Ali Ahmed', (select id from public.selecoes where codigo='CAN')),
('Jonathan Osorio', (select id from public.selecoes where codigo='CAN')),
('Promise David', (select id from public.selecoes where codigo='CAN')),
('Nathan Saliba', (select id from public.selecoes where codigo='CAN')),
('Jayden Nelson', (select id from public.selecoes where codigo='CAN')),

-- Grupo B: SUI (Switzerland)
('Denis Zakaria', (select id from public.selecoes where codigo='SUI')),
('Breel Embolo', (select id from public.selecoes where codigo='SUI')),
('Remo Freuler', (select id from public.selecoes where codigo='SUI')),
('Johan Manzambi', (select id from public.selecoes where codigo='SUI')),
('Granit Xhaka', (select id from public.selecoes where codigo='SUI')),
('Dan Ndoye', (select id from public.selecoes where codigo='SUI')),
('Ardon Jashari', (select id from public.selecoes where codigo='SUI')),
('Djibril Sow', (select id from public.selecoes where codigo='SUI')),
('Christian Fassnacht', (select id from public.selecoes where codigo='SUI')),
('Rubén Vargas', (select id from public.selecoes where codigo='SUI')),
('Noah Okafor', (select id from public.selecoes where codigo='SUI')),
('Michel Aebischer', (select id from public.selecoes where codigo='SUI')),
('Fabian Rieder', (select id from public.selecoes where codigo='SUI')),
('Zeki Amdouni', (select id from public.selecoes where codigo='SUI')),
('Cedric Itten', (select id from public.selecoes where codigo='SUI')),

-- Grupo B: QAT (Qatar)
('Abdulaziz Hatem', (select id from public.selecoes where codigo='QAT')),
('Ahmed Alaaeldin', (select id from public.selecoes where codigo='QAT')),
('Edmilson Junior', (select id from public.selecoes where codigo='QAT')),
('Mohammed Muntari', (select id from public.selecoes where codigo='QAT')),
('Hassan Al-Haydos', (select id from public.selecoes where codigo='QAT')),
('Akram Afif', (select id from public.selecoes where codigo='QAT')),
('Karim Boudiaf', (select id from public.selecoes where codigo='QAT')),
('Yusuf Abdurisag', (select id from public.selecoes where codigo='QAT')),
('Ahmed Al-Ganehi', (select id from public.selecoes where codigo='QAT')),
('Almoez Ali', (select id from public.selecoes where codigo='QAT')),
('Ahmed Fathy', (select id from public.selecoes where codigo='QAT')),
('Assim Madibo', (select id from public.selecoes where codigo='QAT')),
('Tahsin Jamshid', (select id from public.selecoes where codigo='QAT')),
('Mohamed Manai', (select id from public.selecoes where codigo='QAT')),

-- Grupo B: BIH (Bosnia and Herzegovina)
('Benjamin Tahirović', (select id from public.selecoes where codigo='BIH')),
('Armin Gigović', (select id from public.selecoes where codigo='BIH')),
('Samed Baždar', (select id from public.selecoes where codigo='BIH')),
('Ermedin Demirović', (select id from public.selecoes where codigo='BIH')),
('Edin Džeko', (select id from public.selecoes where codigo='BIH')),
('Ivan Bašić', (select id from public.selecoes where codigo='BIH')),
('Ivan Šunjić', (select id from public.selecoes where codigo='BIH')),
('Amar Memić', (select id from public.selecoes where codigo='BIH')),
('Amir Hadžiahmetović', (select id from public.selecoes where codigo='BIH')),
('Dženis Burnić', (select id from public.selecoes where codigo='BIH')),
('Kerim Alajbegović', (select id from public.selecoes where codigo='BIH')),
('Esmir Bajraktarević', (select id from public.selecoes where codigo='BIH')),
('Haris Tabaković', (select id from public.selecoes where codigo='BIH')),
('Jovo Lukić', (select id from public.selecoes where codigo='BIH')),
('Ermin Mahmić', (select id from public.selecoes where codigo='BIH')),

-- Grupo C: BRA (Brazil)
('Éderson Silva', (select id from public.selecoes where codigo='BRA')),
('Casemiro', (select id from public.selecoes where codigo='BRA')),
('Vinícius Júnior', (select id from public.selecoes where codigo='BRA')),
('Bruno Guimarães', (select id from public.selecoes where codigo='BRA')),
('Matheus Cunha', (select id from public.selecoes where codigo='BRA')),
('Neymar', (select id from public.selecoes where codigo='BRA')),
('Raphinha', (select id from public.selecoes where codigo='BRA')),
('Fabinho', (select id from public.selecoes where codigo='BRA')),
('Danilo Santos', (select id from public.selecoes where codigo='BRA')),
('Endrick', (select id from public.selecoes where codigo='BRA')),
('Lucas Paquetá', (select id from public.selecoes where codigo='BRA')),
('Luiz Henrique', (select id from public.selecoes where codigo='BRA')),
('Gabriel Martinelli', (select id from public.selecoes where codigo='BRA')),
('Igor Thiago', (select id from public.selecoes where codigo='BRA')),
('Rayan', (select id from public.selecoes where codigo='BRA')),

-- Grupo C: MAR (Morocco)
('Sofyan Amrabat', (select id from public.selecoes where codigo='MAR')),
('Ayyoub Bouaddi', (select id from public.selecoes where codigo='MAR')),
('Chemsdine Talbi', (select id from public.selecoes where codigo='MAR')),
('Azzedine Ounahi', (select id from public.selecoes where codigo='MAR')),
('Soufiane Rahimi', (select id from public.selecoes where codigo='MAR')),
('Brahim Díaz', (select id from public.selecoes where codigo='MAR')),
('Ismael Saibari', (select id from public.selecoes where codigo='MAR')),
('Samir El Mourabet', (select id from public.selecoes where codigo='MAR')),
('Gessime Yassine', (select id from public.selecoes where codigo='MAR')),
('Amine Sbaï', (select id from public.selecoes where codigo='MAR')),
('Ayoub El Kaabi', (select id from public.selecoes where codigo='MAR')),
('Ayoube Amaimouni', (select id from public.selecoes where codigo='MAR')),
('Bilal El Khannouss', (select id from public.selecoes where codigo='MAR')),
('Neil El Aynaoui', (select id from public.selecoes where codigo='MAR')),

-- Grupo C: HAI (Haiti)
('Carl Sainté', (select id from public.selecoes where codigo='HAI')),
('Derrick Etienne Jr.', (select id from public.selecoes where codigo='HAI')),
('Duckens Nazon', (select id from public.selecoes where codigo='HAI')),
('Jean-Ricner Bellegarde', (select id from public.selecoes where codigo='HAI')),
('Louicius Deedson', (select id from public.selecoes where codigo='HAI')),
('Ruben Providence', (select id from public.selecoes where codigo='HAI')),
('Lenny Joseph', (select id from public.selecoes where codigo='HAI')),
('Danley Jean Jacques', (select id from public.selecoes where codigo='HAI')),
('Wilson Isidor', (select id from public.selecoes where codigo='HAI')),
('Yassin Fortuné', (select id from public.selecoes where codigo='HAI')),
('Frantzdy Pierrot', (select id from public.selecoes where codigo='HAI')),
('Josué Casimir', (select id from public.selecoes where codigo='HAI')),
('Dominique Simon', (select id from public.selecoes where codigo='HAI')),
('Woodensky Pierre', (select id from public.selecoes where codigo='HAI')),

-- Grupo C: SCO (Scotland)
('Scott McTominay', (select id from public.selecoes where codigo='SCO')),
('John McGinn', (select id from public.selecoes where codigo='SCO')),
('Tyler Fletcher', (select id from public.selecoes where codigo='SCO')),
('Lyndon Dykes', (select id from public.selecoes where codigo='SCO')),
('Ché Adams', (select id from public.selecoes where codigo='SCO')),
('Ryan Christie', (select id from public.selecoes where codigo='SCO')),
('Ross Stewart', (select id from public.selecoes where codigo='SCO')),
('Ben Gannon-Doak', (select id from public.selecoes where codigo='SCO')),
('George Hirst', (select id from public.selecoes where codigo='SCO')),
('Lewis Ferguson', (select id from public.selecoes where codigo='SCO')),
('Lawrence Shankland', (select id from public.selecoes where codigo='SCO')),
('Kenny McLean', (select id from public.selecoes where codigo='SCO')),
('Findlay Curtis', (select id from public.selecoes where codigo='SCO')),

-- Grupo D: USA (United States)
('Tyler Adams', (select id from public.selecoes where codigo='USA')),
('Giovanni Reyna', (select id from public.selecoes where codigo='USA')),
('Weston McKennie', (select id from public.selecoes where codigo='USA')),
('Ricardo Pepi', (select id from public.selecoes where codigo='USA')),
('Christian Pulisic', (select id from public.selecoes where codigo='USA')),
('Brenden Aaronson', (select id from public.selecoes where codigo='USA')),
('Sebastian Berhalter', (select id from public.selecoes where codigo='USA')),
('Cristian Roldan', (select id from public.selecoes where codigo='USA')),
('Malik Tillman', (select id from public.selecoes where codigo='USA')),
('Haji Wright', (select id from public.selecoes where codigo='USA')),
('Folarin Balogun', (select id from public.selecoes where codigo='USA')),
('Timothy Weah', (select id from public.selecoes where codigo='USA')),
('Alejandro Zendejas', (select id from public.selecoes where codigo='USA')),

-- Grupo D: PAR (Paraguay)
('Ramón Sosa', (select id from public.selecoes where codigo='PAR')),
('Diego Gómez', (select id from public.selecoes where codigo='PAR')),
('Antonio Sanabria', (select id from public.selecoes where codigo='PAR')),
('Miguel Almirón', (select id from public.selecoes where codigo='PAR')),
('Maurício', (select id from public.selecoes where codigo='PAR')),
('Andrés Cubas', (select id from public.selecoes where codigo='PAR')),
('Damián Bobadilla', (select id from public.selecoes where codigo='PAR')),
('Kaku', (select id from public.selecoes where codigo='PAR')),
('Álex Arce', (select id from public.selecoes where codigo='PAR')),
('Julio Enciso', (select id from public.selecoes where codigo='PAR')),
('Braian Ojeda', (select id from public.selecoes where codigo='PAR')),
('Gabriel Ávalos', (select id from public.selecoes where codigo='PAR')),
('Matías Galarza', (select id from public.selecoes where codigo='PAR')),
('Gustavo Caballero', (select id from public.selecoes where codigo='PAR')),
('Isidro Pitta', (select id from public.selecoes where codigo='PAR')),

-- Grupo D: AUS (Australia)
('Mathew Leckie', (select id from public.selecoes where codigo='AUS')),
('Connor Metcalfe', (select id from public.selecoes where codigo='AUS')),
('Mohamed Touré', (select id from public.selecoes where codigo='AUS')),
('Ajdin Hrustic', (select id from public.selecoes where codigo='AUS')),
('Awer Mabil', (select id from public.selecoes where codigo='AUS')),
('Aiden O''Neill', (select id from public.selecoes where codigo='AUS')),
('Cammy Devlin', (select id from public.selecoes where codigo='AUS')),
('Nestory Irankunda', (select id from public.selecoes where codigo='AUS')),
('Cristian Volpato', (select id from public.selecoes where codigo='AUS')),
('Jackson Irvine', (select id from public.selecoes where codigo='AUS')),
('Nishan Velupillay', (select id from public.selecoes where codigo='AUS')),
('Paul Okon-Engstler', (select id from public.selecoes where codigo='AUS')),
('Tete Yengi', (select id from public.selecoes where codigo='AUS')),

-- Grupo D: TUR (Turkey)
('Salih Özcan', (select id from public.selecoes where codigo='TUR')),
('Orkun Kökçü', (select id from public.selecoes where codigo='TUR')),
('Kerem Aktürkoğlu', (select id from public.selecoes where codigo='TUR')),
('Arda Güler', (select id from public.selecoes where codigo='TUR')),
('Deniz Gül', (select id from public.selecoes where codigo='TUR')),
('Hakan Çalhanoğlu', (select id from public.selecoes where codigo='TUR')),
('Kenan Yıldız', (select id from public.selecoes where codigo='TUR')),
('İsmail Yüksek', (select id from public.selecoes where codigo='TUR')),
('İrfan Can Kahveci', (select id from public.selecoes where codigo='TUR')),
('Yunus Akgün', (select id from public.selecoes where codigo='TUR')),
('Barış Alper Yılmaz', (select id from public.selecoes where codigo='TUR')),
('Kaan Ayhan', (select id from public.selecoes where codigo='TUR')),
('Oğuz Aydın', (select id from public.selecoes where codigo='TUR')),
('Can Uzun', (select id from public.selecoes where codigo='TUR')),

-- Grupo E: GER (Germany)
('Aleksandar Pavlović', (select id from public.selecoes where codigo='GER')),
('Kai Havertz', (select id from public.selecoes where codigo='GER')),
('Leon Goretzka', (select id from public.selecoes where codigo='GER')),
('Jamie Leweling', (select id from public.selecoes where codigo='GER')),
('Jamal Musiala', (select id from public.selecoes where codigo='GER')),
('Nick Woltemade', (select id from public.selecoes where codigo='GER')),
('Pascal Groß', (select id from public.selecoes where codigo='GER')),
('Maximilian Beier', (select id from public.selecoes where codigo='GER')),
('Angelo Stiller', (select id from public.selecoes where codigo='GER')),
('Florian Wirtz', (select id from public.selecoes where codigo='GER')),
('Leroy Sané', (select id from public.selecoes where codigo='GER')),
('Nadiem Amiri', (select id from public.selecoes where codigo='GER')),
('Felix Nmecha', (select id from public.selecoes where codigo='GER')),
('Assan Ouédraogo', (select id from public.selecoes where codigo='GER')),
('Deniz Undav', (select id from public.selecoes where codigo='GER')),

-- Grupo E: CUW (Curaçao)
('Godfried Roemeratoe', (select id from public.selecoes where codigo='CUW')),
('Juninho Bacuna', (select id from public.selecoes where codigo='CUW')),
('Livano Comenencia', (select id from public.selecoes where codigo='CUW')),
('Jürgen Locadia', (select id from public.selecoes where codigo='CUW')),
('Leandro Bacuna', (select id from public.selecoes where codigo='CUW')),
('Jeremy Antonisse', (select id from public.selecoes where codigo='CUW')),
('Sontje Hansen', (select id from public.selecoes where codigo='CUW')),
('Tyrese Noslin', (select id from public.selecoes where codigo='CUW')),
('Kenji Gorré', (select id from public.selecoes where codigo='CUW')),
('Ar''jany Martha', (select id from public.selecoes where codigo='CUW')),
('Jearl Margaritha', (select id from public.selecoes where codigo='CUW')),
('Brandley Kuwas', (select id from public.selecoes where codigo='CUW')),
('Gervane Kastaneer', (select id from public.selecoes where codigo='CUW')),
('Tahith Chong', (select id from public.selecoes where codigo='CUW')),
('Kevin Felida', (select id from public.selecoes where codigo='CUW')),

-- Grupo E: CIV (Ivory Coast)
('Jean Michaël Seri', (select id from public.selecoes where codigo='CIV')),
('Seko Fofana', (select id from public.selecoes where codigo='CIV')),
('Franck Kessié', (select id from public.selecoes where codigo='CIV')),
('Ange-Yoan Bonny', (select id from public.selecoes where codigo='CIV')),
('Simon Adingra', (select id from public.selecoes where codigo='CIV')),
('Yan Diomande', (select id from public.selecoes where codigo='CIV')),
('Elye Wahi', (select id from public.selecoes where codigo='CIV')),
('Oumar Diakité', (select id from public.selecoes where codigo='CIV')),
('Amad Diallo', (select id from public.selecoes where codigo='CIV')),
('Ibrahim Sangaré', (select id from public.selecoes where codigo='CIV')),
('Nicolas Pépé', (select id from public.selecoes where codigo='CIV')),
('Evann Guessand', (select id from public.selecoes where codigo='CIV')),
('Bazoumana Touré', (select id from public.selecoes where codigo='CIV')),
('Parfait Guiagon', (select id from public.selecoes where codigo='CIV')),
('Christ Inao Oulaï', (select id from public.selecoes where codigo='CIV')),

-- Grupo E: ECU (Ecuador)
('Jordy Alcívar', (select id from public.selecoes where codigo='ECU')),
('Anthony Valencia', (select id from public.selecoes where codigo='ECU')),
('John Yeboah', (select id from public.selecoes where codigo='ECU')),
('Kendry Páez', (select id from public.selecoes where codigo='ECU')),
('Kevin Rodríguez', (select id from public.selecoes where codigo='ECU')),
('Enner Valencia', (select id from public.selecoes where codigo='ECU')),
('Alan Minda', (select id from public.selecoes where codigo='ECU')),
('Pedro Vite', (select id from public.selecoes where codigo='ECU')),
('Jordy Caicedo', (select id from public.selecoes where codigo='ECU')),
('Denil Castillo', (select id from public.selecoes where codigo='ECU')),
('Gonzalo Plata', (select id from public.selecoes where codigo='ECU')),
('Nilson Angulo', (select id from public.selecoes where codigo='ECU')),
('Alan Franco', (select id from public.selecoes where codigo='ECU')),
('Moisés Caicedo', (select id from public.selecoes where codigo='ECU')),
('Jeremy Arévalo', (select id from public.selecoes where codigo='ECU')),

-- Grupo F: NED (Netherlands)
('Marten de Roon', (select id from public.selecoes where codigo='NED')),
('Justin Kluivert', (select id from public.selecoes where codigo='NED')),
('Ryan Gravenberch', (select id from public.selecoes where codigo='NED')),
('Wout Weghorst', (select id from public.selecoes where codigo='NED')),
('Memphis Depay', (select id from public.selecoes where codigo='NED')),
('Cody Gakpo', (select id from public.selecoes where codigo='NED')),
('Tijjani Reijnders', (select id from public.selecoes where codigo='NED')),
('Guus Til', (select id from public.selecoes where codigo='NED')),
('Noa Lang', (select id from public.selecoes where codigo='NED')),
('Donyell Malen', (select id from public.selecoes where codigo='NED')),
('Brian Brobbey', (select id from public.selecoes where codigo='NED')),
('Teun Koopmeiners', (select id from public.selecoes where codigo='NED')),
('Frenkie de Jong', (select id from public.selecoes where codigo='NED')),
('Crysencio Summerville', (select id from public.selecoes where codigo='NED')),
('Quinten Timber', (select id from public.selecoes where codigo='NED')),

-- Grupo F: JPN (Japan)
('Shuto Machino', (select id from public.selecoes where codigo='JPN')),
('Ao Tanaka', (select id from public.selecoes where codigo='JPN')),
('Takefusa Kubo', (select id from public.selecoes where codigo='JPN')),
('Keisuke Gotō', (select id from public.selecoes where codigo='JPN')),
('Ritsu Dōan', (select id from public.selecoes where codigo='JPN')),
('Daizen Maeda', (select id from public.selecoes where codigo='JPN')),
('Keito Nakamura', (select id from public.selecoes where codigo='JPN')),
('Junya Itō', (select id from public.selecoes where codigo='JPN')),
('Daichi Kamada', (select id from public.selecoes where codigo='JPN')),
('Yuito Suzuki', (select id from public.selecoes where codigo='JPN')),
('Ayase Ueda', (select id from public.selecoes where codigo='JPN')),
('Kōki Ogawa', (select id from public.selecoes where codigo='JPN')),
('Kaishū Sano', (select id from public.selecoes where codigo='JPN')),
('Kento Shiogai', (select id from public.selecoes where codigo='JPN')),

-- Grupo F: SWE (Sweden)
('Lucas Bergvall', (select id from public.selecoes where codigo='SWE')),
('Alexander Isak', (select id from public.selecoes where codigo='SWE')),
('Benjamin Nygren', (select id from public.selecoes where codigo='SWE')),
('Anthony Elanga', (select id from public.selecoes where codigo='SWE')),
('Ken Sema', (select id from public.selecoes where codigo='SWE')),
('Jesper Karlström', (select id from public.selecoes where codigo='SWE')),
('Viktor Gyökeres', (select id from public.selecoes where codigo='SWE')),
('Yasin Ayari', (select id from public.selecoes where codigo='SWE')),
('Mattias Svanberg', (select id from public.selecoes where codigo='SWE')),
('Besfort Zeneli', (select id from public.selecoes where codigo='SWE')),
('Gustaf Nilsson', (select id from public.selecoes where codigo='SWE')),
('Taha Ali', (select id from public.selecoes where codigo='SWE')),

-- Grupo F: TUN (Tunisia)
('Elias Achouri', (select id from public.selecoes where codigo='TUN')),
('Elias Saad', (select id from public.selecoes where codigo='TUN')),
('Hazem Mastouri', (select id from public.selecoes where codigo='TUN')),
('Hannibal Mejbri', (select id from public.selecoes where codigo='TUN')),
('Ismaël Gharbi', (select id from public.selecoes where codigo='TUN')),
('Rani Khedira', (select id from public.selecoes where codigo='TUN')),
('Khalil Ayari', (select id from public.selecoes where codigo='TUN')),
('Hadj Mahmoud', (select id from public.selecoes where codigo='TUN')),
('Ellyes Skhiri', (select id from public.selecoes where codigo='TUN')),
('Rayan Elloumi', (select id from public.selecoes where codigo='TUN')),
('Firas Chaouat', (select id from public.selecoes where codigo='TUN')),
('Anis Ben Slimane', (select id from public.selecoes where codigo='TUN')),
('Sebastian Tounekti', (select id from public.selecoes where codigo='TUN')),

-- Grupo G: BEL (Belgium)
('Axel Witsel', (select id from public.selecoes where codigo='BEL')),
('Kevin De Bruyne', (select id from public.selecoes where codigo='BEL')),
('Youri Tielemans', (select id from public.selecoes where codigo='BEL')),
('Romelu Lukaku', (select id from public.selecoes where codigo='BEL')),
('Leandro Trossard', (select id from public.selecoes where codigo='BEL')),
('Jérémy Doku', (select id from public.selecoes where codigo='BEL')),
('Dodi Lukébakio', (select id from public.selecoes where codigo='BEL')),
('Charles De Ketelaere', (select id from public.selecoes where codigo='BEL')),
('Diego Moreira', (select id from public.selecoes where codigo='BEL')),
('Hans Vanaken', (select id from public.selecoes where codigo='BEL')),
('Alexis Saelemaekers', (select id from public.selecoes where codigo='BEL')),
('Nicolas Raskin', (select id from public.selecoes where codigo='BEL')),
('Amadou Onana', (select id from public.selecoes where codigo='BEL')),
('Matias Fernandez-Pardo', (select id from public.selecoes where codigo='BEL')),

-- Grupo G: EGY (Egypt)
('Trézéguet', (select id from public.selecoes where codigo='EGY')),
('Emam Ashour', (select id from public.selecoes where codigo='EGY')),
('Hamza Abdelkarim', (select id from public.selecoes where codigo='EGY')),
('Mohamed Salah', (select id from public.selecoes where codigo='EGY')),
('Mostafa Ziko', (select id from public.selecoes where codigo='EGY')),
('Haissem Hassan', (select id from public.selecoes where codigo='EGY')),
('Hamdy Fathy', (select id from public.selecoes where codigo='EGY')),
('Mohanad Lasheen', (select id from public.selecoes where codigo='EGY')),
('Nabil Emad', (select id from public.selecoes where codigo='EGY')),
('Marwan Attia', (select id from public.selecoes where codigo='EGY')),
('Ibrahim Adel', (select id from public.selecoes where codigo='EGY')),
('Mahmoud Saber', (select id from public.selecoes where codigo='EGY')),
('Omar Marmoush', (select id from public.selecoes where codigo='EGY')),
('Zizo', (select id from public.selecoes where codigo='EGY')),

-- Grupo G: IRN (Iran)
('Saeid Ezatolahi', (select id from public.selecoes where codigo='IRN')),
('Alireza Jahanbakhsh', (select id from public.selecoes where codigo='IRN')),
('Mohammad Mohebi', (select id from public.selecoes where codigo='IRN')),
('Mehdi Taremi', (select id from public.selecoes where codigo='IRN')),
('Mehdi Ghayedi', (select id from public.selecoes where codigo='IRN')),
('Ali Alipour', (select id from public.selecoes where codigo='IRN')),
('Saman Ghoddos', (select id from public.selecoes where codigo='IRN')),
('Rouzbeh Cheshmi', (select id from public.selecoes where codigo='IRN')),
('Mehdi Torabi', (select id from public.selecoes where codigo='IRN')),
('Amirhossein Hosseinzadeh', (select id from public.selecoes where codigo='IRN')),
('Shahriyar Moghanlou', (select id from public.selecoes where codigo='IRN')),
('Mohammad Ghorbani', (select id from public.selecoes where codigo='IRN')),
('Dennis Eckert', (select id from public.selecoes where codigo='IRN')),
('Amirmohammad Razzaghinia', (select id from public.selecoes where codigo='IRN')),

-- Grupo G: NZL (New Zealand)
('Joe Bell', (select id from public.selecoes where codigo='NZL')),
('Matthew Garbett', (select id from public.selecoes where codigo='NZL')),
('Marko Stamenić', (select id from public.selecoes where codigo='NZL')),
('Chris Wood', (select id from public.selecoes where codigo='NZL')),
('Sarpreet Singh', (select id from public.selecoes where codigo='NZL')),
('Elijah Just', (select id from public.selecoes where codigo='NZL')),
('Alex Rufer', (select id from public.selecoes where codigo='NZL')),
('Kosta Barbarouses', (select id from public.selecoes where codigo='NZL')),
('Ben Waine', (select id from public.selecoes where codigo='NZL')),
('Ben Old', (select id from public.selecoes where codigo='NZL')),
('Callum McCowatt', (select id from public.selecoes where codigo='NZL')),
('Jesse Randall', (select id from public.selecoes where codigo='NZL')),
('Ryan Thomas', (select id from public.selecoes where codigo='NZL')),
('Lachlan Bayliss', (select id from public.selecoes where codigo='NZL')),

-- Grupo H: ESP (Spain)
('Mikel Merino', (select id from public.selecoes where codigo='ESP')),
('Ferran Torres', (select id from public.selecoes where codigo='ESP')),
('Fabián Ruiz', (select id from public.selecoes where codigo='ESP')),
('Gavi', (select id from public.selecoes where codigo='ESP')),
('Dani Olmo', (select id from public.selecoes where codigo='ESP')),
('Yéremy Pino', (select id from public.selecoes where codigo='ESP')),
('Álex Baena', (select id from public.selecoes where codigo='ESP')),
('Rodri', (select id from public.selecoes where codigo='ESP')),
('Nico Williams', (select id from public.selecoes where codigo='ESP')),
('Martín Zubimendi', (select id from public.selecoes where codigo='ESP')),
('Lamine Yamal', (select id from public.selecoes where codigo='ESP')),
('Pedri', (select id from public.selecoes where codigo='ESP')),
('Mikel Oyarzabal', (select id from public.selecoes where codigo='ESP')),
('Víctor Muñoz', (select id from public.selecoes where codigo='ESP')),
('Borja Iglesias', (select id from public.selecoes where codigo='ESP')),

-- Grupo H: CPV (Cape Verde)
('Kevin Pina', (select id from public.selecoes where codigo='CPV')),
('Jovane Cabral', (select id from public.selecoes where codigo='CPV')),
('João Paulo', (select id from public.selecoes where codigo='CPV')),
('Gilson Benchimol', (select id from public.selecoes where codigo='CPV')),
('Jamiro Monteiro', (select id from public.selecoes where codigo='CPV')),
('Garry Rodrigues', (select id from public.selecoes where codigo='CPV')),
('Deroy Duarte', (select id from public.selecoes where codigo='CPV')),
('Laros Duarte', (select id from public.selecoes where codigo='CPV')),
('Yannick Semedo', (select id from public.selecoes where codigo='CPV')),
('Willy Semedo', (select id from public.selecoes where codigo='CPV')),
('Telmo Arcanjo', (select id from public.selecoes where codigo='CPV')),
('Dailon Livramento', (select id from public.selecoes where codigo='CPV')),
('Ryan Mendes', (select id from public.selecoes where codigo='CPV')),
('Nuno da Costa', (select id from public.selecoes where codigo='CPV')),
('Hélio Varela', (select id from public.selecoes where codigo='CPV')),

-- Grupo H: KSA (Saudi Arabia)
('Nasser Al-Dawsari', (select id from public.selecoes where codigo='KSA')),
('Musab Al-Juwayr', (select id from public.selecoes where codigo='KSA')),
('Ayman Yahya', (select id from public.selecoes where codigo='KSA')),
('Firas Al-Buraikan', (select id from public.selecoes where codigo='KSA')),
('Salem Al-Dawsari', (select id from public.selecoes where codigo='KSA')),
('Saleh Al-Shehri', (select id from public.selecoes where codigo='KSA')),
('Abdullah Al-Khaibari', (select id from public.selecoes where codigo='KSA')),
('Ziyad Al-Johani', (select id from public.selecoes where codigo='KSA')),
('Khalid Al-Ghannam', (select id from public.selecoes where codigo='KSA')),
('Alaa Al-Hejji', (select id from public.selecoes where codigo='KSA')),
('Abdullah Al-Hamdan', (select id from public.selecoes where codigo='KSA')),
('Sultan Mandash', (select id from public.selecoes where codigo='KSA')),
('Mohamed Kanno', (select id from public.selecoes where codigo='KSA')),

-- Grupo H: URU (Uruguay)
('Manuel Ugarte', (select id from public.selecoes where codigo='URU')),
('Rodrigo Bentancur', (select id from public.selecoes where codigo='URU')),
('Nicolás de la Cruz', (select id from public.selecoes where codigo='URU')),
('Federico Valverde', (select id from public.selecoes where codigo='URU')),
('Darwin Núñez', (select id from public.selecoes where codigo='URU')),
('Giorgian de Arrascaeta', (select id from public.selecoes where codigo='URU')),
('Facundo Pellistri', (select id from public.selecoes where codigo='URU')),
('Agustín Canobbio', (select id from public.selecoes where codigo='URU')),
('Emiliano Martínez', (select id from public.selecoes where codigo='URU')),
('Brian Rodríguez', (select id from public.selecoes where codigo='URU')),
('Rodrigo Aguirre', (select id from public.selecoes where codigo='URU')),
('Maximiliano Araújo', (select id from public.selecoes where codigo='URU')),
('Federico Viñas', (select id from public.selecoes where codigo='URU')),
('Joaquín Piquerez', (select id from public.selecoes where codigo='URU')),
('Juan Manuel Sanabria', (select id from public.selecoes where codigo='URU')),
('Rodrigo Zalazar', (select id from public.selecoes where codigo='URU')),

-- Grupo I: FRA (France)
('Manu Koné', (select id from public.selecoes where codigo='FRA')),
('Ousmane Dembélé', (select id from public.selecoes where codigo='FRA')),
('Aurélien Tchouaméni', (select id from public.selecoes where codigo='FRA')),
('Marcus Thuram', (select id from public.selecoes where codigo='FRA')),
('Kylian Mbappé', (select id from public.selecoes where codigo='FRA')),
('Michael Olise', (select id from public.selecoes where codigo='FRA')),
('Bradley Barcola', (select id from public.selecoes where codigo='FRA')),
('N''Golo Kanté', (select id from public.selecoes where codigo='FRA')),
('Adrien Rabiot', (select id from public.selecoes where codigo='FRA')),
('Warren Zaïre-Emery', (select id from public.selecoes where codigo='FRA')),
('Désiré Doué', (select id from public.selecoes where codigo='FRA')),
('Jean-Philippe Mateta', (select id from public.selecoes where codigo='FRA')),
('Rayan Cherki', (select id from public.selecoes where codigo='FRA')),
('Maghnes Akliouche', (select id from public.selecoes where codigo='FRA')),

-- Grupo I: SEN (Senegal)
('Idrissa Gueye', (select id from public.selecoes where codigo='SEN')),
('Pathé Ciss', (select id from public.selecoes where codigo='SEN')),
('Assane Diao', (select id from public.selecoes where codigo='SEN')),
('Lamine Camara', (select id from public.selecoes where codigo='SEN')),
('Bamba Dieng', (select id from public.selecoes where codigo='SEN')),
('Sadio Mané', (select id from public.selecoes where codigo='SEN')),
('Nicolas Jackson', (select id from public.selecoes where codigo='SEN')),
('Cherif Ndiaye', (select id from public.selecoes where codigo='SEN')),
('Iliman Ndiaye', (select id from public.selecoes where codigo='SEN')),
('Pape Matar Sarr', (select id from public.selecoes where codigo='SEN')),
('Ismaïla Sarr', (select id from public.selecoes where codigo='SEN')),
('Ibrahim Mbaye', (select id from public.selecoes where codigo='SEN')),
('Habib Diarra', (select id from public.selecoes where codigo='SEN')),
('Bara Sapoko Ndiaye', (select id from public.selecoes where codigo='SEN')),
('Pape Gueye', (select id from public.selecoes where codigo='SEN')),

-- Grupo I: NOR (Norway)
('Morten Thorsby', (select id from public.selecoes where codigo='NOR')),
('Patrick Berg', (select id from public.selecoes where codigo='NOR')),
('Alexander Sørloth', (select id from public.selecoes where codigo='NOR')),
('Sander Berge', (select id from public.selecoes where codigo='NOR')),
('Erling Haaland', (select id from public.selecoes where codigo='NOR')),
('Martin Ødegaard', (select id from public.selecoes where codigo='NOR')),
('Jørgen Strand Larsen', (select id from public.selecoes where codigo='NOR')),
('Fredrik Aursnes', (select id from public.selecoes where codigo='NOR')),
('Kristian Thorstvedt', (select id from public.selecoes where codigo='NOR')),
('Thelo Aasgaard', (select id from public.selecoes where codigo='NOR')),
('Antonio Nusa', (select id from public.selecoes where codigo='NOR')),
('Andreas Schjelderup', (select id from public.selecoes where codigo='NOR')),
('Oscar Bobb', (select id from public.selecoes where codigo='NOR')),
('Jens Petter Hauge', (select id from public.selecoes where codigo='NOR')),
('Julian Ryerson', (select id from public.selecoes where codigo='NOR')),

-- Grupo I: IRQ (Iraq)
('Youssef Amyn', (select id from public.selecoes where codigo='IRQ')),
('Ibrahim Bayesh', (select id from public.selecoes where codigo='IRQ')),
('Ali Al-Hamadi', (select id from public.selecoes where codigo='IRQ')),
('Mohanad Ali', (select id from public.selecoes where codigo='IRQ')),
('Ahmed Qasem', (select id from public.selecoes where codigo='IRQ')),
('Ali Yousif', (select id from public.selecoes where codigo='IRQ')),
('Zidane Iqbal', (select id from public.selecoes where codigo='IRQ')),
('Amir Al-Ammari', (select id from public.selecoes where codigo='IRQ')),
('Ali Jasim', (select id from public.selecoes where codigo='IRQ')),
('Aymen Hussein', (select id from public.selecoes where codigo='IRQ')),
('Kevin Yakob', (select id from public.selecoes where codigo='IRQ')),
('Aimar Sher', (select id from public.selecoes where codigo='IRQ')),
('Marko Farji', (select id from public.selecoes where codigo='IRQ')),
('Zaid Ismail', (select id from public.selecoes where codigo='IRQ')),

-- Grupo J: ARG (Argentina)
('Leandro Paredes', (select id from public.selecoes where codigo='ARG')),
('Rodrigo De Paul', (select id from public.selecoes where codigo='ARG')),
('Valentín Barco', (select id from public.selecoes where codigo='ARG')),
('Julián Alvarez', (select id from public.selecoes where codigo='ARG')),
('Lionel Messi', (select id from public.selecoes where codigo='ARG')),
('Giovani Lo Celso', (select id from public.selecoes where codigo='ARG')),
('Exequiel Palacios', (select id from public.selecoes where codigo='ARG')),
('Nicolás González', (select id from public.selecoes where codigo='ARG')),
('Thiago Almada', (select id from public.selecoes where codigo='ARG')),
('Giuliano Simeone', (select id from public.selecoes where codigo='ARG')),
('Nico Paz', (select id from public.selecoes where codigo='ARG')),
('Alexis Mac Allister', (select id from public.selecoes where codigo='ARG')),
('José Manuel López', (select id from public.selecoes where codigo='ARG')),
('Lautaro Martínez', (select id from public.selecoes where codigo='ARG')),
('Enzo Fernández', (select id from public.selecoes where codigo='ARG')),

-- Grupo J: ALG (Algeria)
('Ramiz Zerrouki', (select id from public.selecoes where codigo='ALG')),
('Riyad Mahrez', (select id from public.selecoes where codigo='ALG')),
('Houssem Aouar', (select id from public.selecoes where codigo='ALG')),
('Amine Gouiri', (select id from public.selecoes where codigo='ALG')),
('Farès Chaïbi', (select id from public.selecoes where codigo='ALG')),
('Anis Hadj Moussa', (select id from public.selecoes where codigo='ALG')),
('Nadhir Benbouali', (select id from public.selecoes where codigo='ALG')),
('Hicham Boudaoui', (select id from public.selecoes where codigo='ALG')),
('Mohamed Amoura', (select id from public.selecoes where codigo='ALG')),
('Nabil Bentaleb', (select id from public.selecoes where codigo='ALG')),
('Adil Boulbina', (select id from public.selecoes where codigo='ALG')),
('Ibrahim Maza', (select id from public.selecoes where codigo='ALG')),
('Yacine Titraoui', (select id from public.selecoes where codigo='ALG')),
('Farès Ghedjemis', (select id from public.selecoes where codigo='ALG')),

-- Grupo J: AUT (Austria)
('Xaver Schlager', (select id from public.selecoes where codigo='AUT')),
('Nicolas Seiwald', (select id from public.selecoes where codigo='AUT')),
('Marko Arnautović', (select id from public.selecoes where codigo='AUT')),
('Marcel Sabitzer', (select id from public.selecoes where codigo='AUT')),
('Florian Grillitsch', (select id from public.selecoes where codigo='AUT')),
('Michael Gregoritsch', (select id from public.selecoes where codigo='AUT')),
('Saša Kalajdžić', (select id from public.selecoes where codigo='AUT')),
('Carney Chukwuemeka', (select id from public.selecoes where codigo='AUT')),
('Romano Schmid', (select id from public.selecoes where codigo='AUT')),
('Dejan Ljubičić', (select id from public.selecoes where codigo='AUT')),
('Konrad Laimer', (select id from public.selecoes where codigo='AUT')),
('Patrick Wimmer', (select id from public.selecoes where codigo='AUT')),
('Alexander Prass', (select id from public.selecoes where codigo='AUT')),
('Paul Wanner', (select id from public.selecoes where codigo='AUT')),
('Alessandro Schöpf', (select id from public.selecoes where codigo='AUT')),

-- Grupo J: JOR (Jordan)
('Amer Jamous', (select id from public.selecoes where codigo='JOR')),
('Mohammad Abu Zrayq', (select id from public.selecoes where codigo='JOR')),
('Noor Al-Rawabdeh', (select id from public.selecoes where codigo='JOR')),
('Ali Olwan', (select id from public.selecoes where codigo='JOR')),
('Musa Al-Taamari', (select id from public.selecoes where codigo='JOR')),
('Odeh Al-Fakhouri', (select id from public.selecoes where codigo='JOR')),
('Mahmoud Al-Mardi', (select id from public.selecoes where codigo='JOR')),
('Rajaei Ayed', (select id from public.selecoes where codigo='JOR')),
('Ibrahim Sadeh', (select id from public.selecoes where codigo='JOR')),
('Mohammad Taha', (select id from public.selecoes where codigo='JOR')),
('Mohannad Abu Taha', (select id from public.selecoes where codigo='JOR')),
('Nizar Al-Rashdan', (select id from public.selecoes where codigo='JOR')),
('Ali Azaizeh', (select id from public.selecoes where codigo='JOR')),
('Mohammad Al-Dawoud', (select id from public.selecoes where codigo='JOR')),

-- Grupo K: POR (Portugal)
('Matheus Nunes', (select id from public.selecoes where codigo='POR')),
('Cristiano Ronaldo', (select id from public.selecoes where codigo='POR')),
('Bruno Fernandes', (select id from public.selecoes where codigo='POR')),
('Gonçalo Ramos', (select id from public.selecoes where codigo='POR')),
('Bernardo Silva', (select id from public.selecoes where codigo='POR')),
('João Félix', (select id from public.selecoes where codigo='POR')),
('João Neves', (select id from public.selecoes where codigo='POR')),
('Francisco Trincão', (select id from public.selecoes where codigo='POR')),
('Rafael Leão', (select id from public.selecoes where codigo='POR')),
('Pedro Neto', (select id from public.selecoes where codigo='POR')),
('Gonçalo Guedes', (select id from public.selecoes where codigo='POR')),
('Rúben Neves', (select id from public.selecoes where codigo='POR')),
('Vitinha', (select id from public.selecoes where codigo='POR')),
('Francisco Conceição', (select id from public.selecoes where codigo='POR')),

-- Grupo K: UZB (Uzbekistan)
('Akmal Mozgovoy', (select id from public.selecoes where codigo='UZB')),
('Otabek Shukurov', (select id from public.selecoes where codigo='UZB')),
('Jamshid Iskanderov', (select id from public.selecoes where codigo='UZB')),
('Odiljon Hamrobekov', (select id from public.selecoes where codigo='UZB')),
('Jaloliddin Masharipov', (select id from public.selecoes where codigo='UZB')),
('Oston Urunov', (select id from public.selecoes where codigo='UZB')),
('Eldor Shomurodov', (select id from public.selecoes where codigo='UZB')),
('Dostonbek Khamdamov', (select id from public.selecoes where codigo='UZB')),
('Azizjon Ganiev', (select id from public.selecoes where codigo='UZB')),
('Azizbek Amonov', (select id from public.selecoes where codigo='UZB')),
('Igor Sergeev', (select id from public.selecoes where codigo='UZB')),
('Abbosbek Fayzullaev', (select id from public.selecoes where codigo='UZB')),
('Sherzod Esanov', (select id from public.selecoes where codigo='UZB')),

-- Grupo K: COL (Colombia)
('Kevin Castaño', (select id from public.selecoes where codigo='COL')),
('Richard Ríos', (select id from public.selecoes where codigo='COL')),
('Luis Díaz', (select id from public.selecoes where codigo='COL')),
('Jorge Carrascal', (select id from public.selecoes where codigo='COL')),
('Jhon Córdoba', (select id from public.selecoes where codigo='COL')),
('James Rodríguez', (select id from public.selecoes where codigo='COL')),
('Jhon Arias', (select id from public.selecoes where codigo='COL')),
('Juan Portilla', (select id from public.selecoes where codigo='COL')),
('Jefferson Lerma', (select id from public.selecoes where codigo='COL')),
('Cucho Hernández', (select id from public.selecoes where codigo='COL')),
('Juan Fernando Quintero', (select id from public.selecoes where codigo='COL')),
('Jaminton Campaz', (select id from public.selecoes where codigo='COL')),
('Luis Suárez', (select id from public.selecoes where codigo='COL')),
('Andrés Gómez', (select id from public.selecoes where codigo='COL')),

-- Grupo K: COD (DR Congo)
('Ngal''ayel Mukau', (select id from public.selecoes where codigo='COD')),
('Nathanaël Mbuku', (select id from public.selecoes where codigo='COD')),
('Samuel Moutoussamy', (select id from public.selecoes where codigo='COD')),
('Brian Cipenga', (select id from public.selecoes where codigo='COD')),
('Théo Bongonda', (select id from public.selecoes where codigo='COD')),
('Gaël Kakuta', (select id from public.selecoes where codigo='COD')),
('Meschak Elia', (select id from public.selecoes where codigo='COD')),
('Noah Sadiki', (select id from public.selecoes where codigo='COD')),
('Aaron Tshibola', (select id from public.selecoes where codigo='COD')),
('Cédric Bakambu', (select id from public.selecoes where codigo='COD')),
('Charles Pickel', (select id from public.selecoes where codigo='COD')),
('Fiston Mayele', (select id from public.selecoes where codigo='COD')),
('Yoane Wissa', (select id from public.selecoes where codigo='COD')),
('Simon Banza', (select id from public.selecoes where codigo='COD')),
('Edo Kayembe', (select id from public.selecoes where codigo='COD')),

-- Grupo L: ENG (England)
('Declan Rice', (select id from public.selecoes where codigo='ENG')),
('Bukayo Saka', (select id from public.selecoes where codigo='ENG')),
('Elliot Anderson', (select id from public.selecoes where codigo='ENG')),
('Harry Kane', (select id from public.selecoes where codigo='ENG')),
('Jude Bellingham', (select id from public.selecoes where codigo='ENG')),
('Marcus Rashford', (select id from public.selecoes where codigo='ENG')),
('Jordan Henderson', (select id from public.selecoes where codigo='ENG')),
('Kobbie Mainoo', (select id from public.selecoes where codigo='ENG')),
('Morgan Rogers', (select id from public.selecoes where codigo='ENG')),
('Anthony Gordon', (select id from public.selecoes where codigo='ENG')),
('Ollie Watkins', (select id from public.selecoes where codigo='ENG')),
('Noni Madueke', (select id from public.selecoes where codigo='ENG')),
('Eberechi Eze', (select id from public.selecoes where codigo='ENG')),
('Ivan Toney', (select id from public.selecoes where codigo='ENG')),

-- Grupo L: CRO (Croatia)
('Nikola Moro', (select id from public.selecoes where codigo='CRO')),
('Mateo Kovačić', (select id from public.selecoes where codigo='CRO')),
('Andrej Kramarić', (select id from public.selecoes where codigo='CRO')),
('Luka Modrić', (select id from public.selecoes where codigo='CRO')),
('Ante Budimir', (select id from public.selecoes where codigo='CRO')),
('Nikola Vlašić', (select id from public.selecoes where codigo='CRO')),
('Ivan Perišić', (select id from public.selecoes where codigo='CRO')),
('Mario Pašalić', (select id from public.selecoes where codigo='CRO')),
('Martin Baturina', (select id from public.selecoes where codigo='CRO')),
('Petar Sučić', (select id from public.selecoes where codigo='CRO')),
('Toni Fruk', (select id from public.selecoes where codigo='CRO')),
('Igor Matanović', (select id from public.selecoes where codigo='CRO')),
('Luka Sučić', (select id from public.selecoes where codigo='CRO')),
('Marco Pašalić', (select id from public.selecoes where codigo='CRO')),
('Petar Musa', (select id from public.selecoes where codigo='CRO')),

-- Grupo L: GHA (Ghana)
('Caleb Yirenkyi', (select id from public.selecoes where codigo='GHA')),
('Thomas Partey', (select id from public.selecoes where codigo='GHA')),
('Abdul Fatawu', (select id from public.selecoes where codigo='GHA')),
('Kwasi Sibo', (select id from public.selecoes where codigo='GHA')),
('Jordan Ayew', (select id from public.selecoes where codigo='GHA')),
('Brandon Thomas-Asante', (select id from public.selecoes where codigo='GHA')),
('Antoine Semenyo', (select id from public.selecoes where codigo='GHA')),
('Christopher Bonsu Baah', (select id from public.selecoes where codigo='GHA')),
('Elisha Owusu', (select id from public.selecoes where codigo='GHA')),
('Iñaki Williams', (select id from public.selecoes where codigo='GHA')),
('Augustine Boakye', (select id from public.selecoes where codigo='GHA')),
('Kamaldeen Sulemana', (select id from public.selecoes where codigo='GHA')),
('Ernest Nuamah', (select id from public.selecoes where codigo='GHA')),
('Prince Kwabena Adu', (select id from public.selecoes where codigo='GHA')),

-- Grupo L: PAN (Panama)
('Cristian Martínez', (select id from public.selecoes where codigo='PAN')),
('José Luis Rodríguez', (select id from public.selecoes where codigo='PAN')),
('Adalberto Carrasquilla', (select id from public.selecoes where codigo='PAN')),
('Tomás Rodríguez', (select id from public.selecoes where codigo='PAN')),
('Ismael Díaz', (select id from public.selecoes where codigo='PAN')),
('Yoel Bárcenas', (select id from public.selecoes where codigo='PAN')),
('José Fajardo', (select id from public.selecoes where codigo='PAN')),
('Cecilio Waterman', (select id from public.selecoes where codigo='PAN')),
('Alberto Quintero', (select id from public.selecoes where codigo='PAN')),
('Aníbal Godoy', (select id from public.selecoes where codigo='PAN')),
('César Yanis', (select id from public.selecoes where codigo='PAN')),
('Azarias Londoño', (select id from public.selecoes where codigo='PAN'));

commit;
