/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBoloesRouteImport } from './routes/_authenticated/boloes'
import { Route as AuthenticatedBoloesIndexRouteImport } from './routes/_authenticated/boloes.index'
import { Route as ApiPublicSbConfigDotjsRouteImport } from './routes/api/public/sb-config[.]js'
import { Route as AuthenticatedPalpitesGruposRouteImport } from './routes/_authenticated/palpites.grupos'
import { Route as AuthenticatedBoloesIdRouteImport } from './routes/_authenticated/boloes.$id'
import { Route as AuthenticatedBoloesEntrarCodigoRouteImport } from './routes/_authenticated/boloes.entrar.$codigo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoloesRoute = AuthenticatedBoloesRouteImport.update({
  id: '/boloes',
  path: '/boloes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoloesIndexRoute =
  AuthenticatedBoloesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBoloesRoute,
  } as any)
const ApiPublicSbConfigDotjsRoute = ApiPublicSbConfigDotjsRouteImport.update({
  id: '/api/public/sb-config.js',
  path: '/api/public/sb-config.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPalpitesGruposRoute =
  AuthenticatedPalpitesGruposRouteImport.update({
    id: '/palpites/grupos',
    path: '/palpites/grupos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoloesIdRoute = AuthenticatedBoloesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedBoloesRoute,
} as any)
const AuthenticatedBoloesEntrarCodigoRoute =
  AuthenticatedBoloesEntrarCodigoRouteImport.update({
    id: '/entrar/$codigo',
    path: '/entrar/$codigo',
    getParentRoute: () => AuthenticatedBoloesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/boloes': typeof AuthenticatedBoloesRouteWithChildren
  '/boloes/$id': typeof AuthenticatedBoloesIdRoute
  '/palpites/grupos': typeof AuthenticatedPalpitesGruposRoute
  '/api/public/sb-config.js': typeof ApiPublicSbConfigDotjsRoute
  '/boloes/': typeof AuthenticatedBoloesIndexRoute
  '/boloes/entrar/$codigo': typeof AuthenticatedBoloesEntrarCodigoRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/boloes/$id': typeof AuthenticatedBoloesIdRoute
  '/palpites/grupos': typeof AuthenticatedPalpitesGruposRoute
  '/api/public/sb-config.js': typeof ApiPublicSbConfigDotjsRoute
  '/boloes': typeof AuthenticatedBoloesIndexRoute
  '/boloes/entrar/$codigo': typeof AuthenticatedBoloesEntrarCodigoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/boloes': typeof AuthenticatedBoloesRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/boloes/$id': typeof AuthenticatedBoloesIdRoute
  '/_authenticated/palpites/grupos': typeof AuthenticatedPalpitesGruposRoute
  '/api/public/sb-config.js': typeof ApiPublicSbConfigDotjsRoute
  '/_authenticated/boloes/': typeof AuthenticatedBoloesIndexRoute
  '/_authenticated/boloes/entrar/$codigo': typeof AuthenticatedBoloesEntrarCodigoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/boloes'
    | '/boloes/$id'
    | '/palpites/grupos'
    | '/api/public/sb-config.js'
    | '/boloes/'
    | '/boloes/entrar/$codigo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/boloes/$id'
    | '/palpites/grupos'
    | '/api/public/sb-config.js'
    | '/boloes'
    | '/boloes/entrar/$codigo'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/boloes'
    | '/_authenticated/'
    | '/_authenticated/boloes/$id'
    | '/_authenticated/palpites/grupos'
    | '/api/public/sb-config.js'
    | '/_authenticated/boloes/'
    | '/_authenticated/boloes/entrar/$codigo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSbConfigDotjsRoute: typeof ApiPublicSbConfigDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boloes': {
      id: '/_authenticated/boloes'
      path: '/boloes'
      fullPath: '/boloes'
      preLoaderRoute: typeof AuthenticatedBoloesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boloes/': {
      id: '/_authenticated/boloes/'
      path: '/'
      fullPath: '/boloes/'
      preLoaderRoute: typeof AuthenticatedBoloesIndexRouteImport
      parentRoute: typeof AuthenticatedBoloesRoute
    }
    '/api/public/sb-config.js': {
      id: '/api/public/sb-config.js'
      path: '/api/public/sb-config.js'
      fullPath: '/api/public/sb-config.js'
      preLoaderRoute: typeof ApiPublicSbConfigDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/palpites/grupos': {
      id: '/_authenticated/palpites/grupos'
      path: '/palpites/grupos'
      fullPath: '/palpites/grupos'
      preLoaderRoute: typeof AuthenticatedPalpitesGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boloes/$id': {
      id: '/_authenticated/boloes/$id'
      path: '/$id'
      fullPath: '/boloes/$id'
      preLoaderRoute: typeof AuthenticatedBoloesIdRouteImport
      parentRoute: typeof AuthenticatedBoloesRoute
    }
    '/_authenticated/boloes/entrar/$codigo': {
      id: '/_authenticated/boloes/entrar/$codigo'
      path: '/entrar/$codigo'
      fullPath: '/boloes/entrar/$codigo'
      preLoaderRoute: typeof AuthenticatedBoloesEntrarCodigoRouteImport
      parentRoute: typeof AuthenticatedBoloesRoute
    }
  }
}

interface AuthenticatedBoloesRouteChildren {
  AuthenticatedBoloesIdRoute: typeof AuthenticatedBoloesIdRoute
  AuthenticatedBoloesIndexRoute: typeof AuthenticatedBoloesIndexRoute
  AuthenticatedBoloesEntrarCodigoRoute: typeof AuthenticatedBoloesEntrarCodigoRoute
}

const AuthenticatedBoloesRouteChildren: AuthenticatedBoloesRouteChildren = {
  AuthenticatedBoloesIdRoute: AuthenticatedBoloesIdRoute,
  AuthenticatedBoloesIndexRoute: AuthenticatedBoloesIndexRoute,
  AuthenticatedBoloesEntrarCodigoRoute: AuthenticatedBoloesEntrarCodigoRoute,
}

const AuthenticatedBoloesRouteWithChildren =
  AuthenticatedBoloesRoute._addFileChildren(AuthenticatedBoloesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBoloesRoute: typeof AuthenticatedBoloesRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPalpitesGruposRoute: typeof AuthenticatedPalpitesGruposRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBoloesRoute: AuthenticatedBoloesRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPalpitesGruposRoute: AuthenticatedPalpitesGruposRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSbConfigDotjsRoute: ApiPublicSbConfigDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
