/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ApiPublicSbConfigDotjsRouteImport } from './routes/api/public/sb-config[.]js'
import { Route as AuthenticatedPalpitesGruposRouteImport } from './routes/_authenticated/palpites.grupos'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSbConfigDotjsRoute = ApiPublicSbConfigDotjsRouteImport.update({
  id: '/api/public/sb-config.js',
  path: '/api/public/sb-config.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPalpitesGruposRoute =
  AuthenticatedPalpitesGruposRouteImport.update({
    id: '/palpites/grupos',
    path: '/palpites/grupos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/palpites/grupos': typeof AuthenticatedPalpitesGruposRoute
  '/api/public/sb-config.js': typeof ApiPublicSbConfigDotjsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/palpites/grupos': typeof AuthenticatedPalpitesGruposRoute
  '/api/public/sb-config.js': typeof ApiPublicSbConfigDotjsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/palpites/grupos': typeof AuthenticatedPalpitesGruposRoute
  '/api/public/sb-config.js': typeof ApiPublicSbConfigDotjsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/palpites/grupos' | '/api/public/sb-config.js'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/palpites/grupos' | '/api/public/sb-config.js'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/palpites/grupos'
    | '/api/public/sb-config.js'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicSbConfigDotjsRoute: typeof ApiPublicSbConfigDotjsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sb-config.js': {
      id: '/api/public/sb-config.js'
      path: '/api/public/sb-config.js'
      fullPath: '/api/public/sb-config.js'
      preLoaderRoute: typeof ApiPublicSbConfigDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/palpites/grupos': {
      id: '/_authenticated/palpites/grupos'
      path: '/palpites/grupos'
      fullPath: '/palpites/grupos'
      preLoaderRoute: typeof AuthenticatedPalpitesGruposRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPalpitesGruposRoute: typeof AuthenticatedPalpitesGruposRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPalpitesGruposRoute: AuthenticatedPalpitesGruposRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicSbConfigDotjsRoute: ApiPublicSbConfigDotjsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
